-- ===========================================================================
-- Sales receivables cycle: invoices and customer receipts.
--
-- This is the first operational document path on top of the Phase 1 ledger.
-- Quotations, sales orders, picking and eTIMS transmission are not here.
-- An invoice posts AR / revenue / output tax through gl.post_entry. A
-- receipt posts bank / AR the same way. Allocation is sub-ledger matching
-- and does not write the ledger again.
--
-- Stock is not issued from this invoice. A parts invoice that must move a
-- serialised unit will do that through inv.post_movement in a later slice,
-- in the same transaction as the AR posting. Shipping without a certificate
-- is a regulatory event; it is not something to sneak in as a side effect
-- of "create invoice".
-- ===========================================================================

set search_path = pg_catalog, public, extensions;

create schema if not exists sales;

comment on schema sales is
  'Customer documents: invoices, receipts and the allocations that match them. Ledger writes go through gl.post_entry.';

-- ---------------------------------------------------------------------------
-- Catalogue: journal sources and document numbers
-- ---------------------------------------------------------------------------

insert into gl.journal_sources (code, name, is_manual, description) values
  ('SALES_INVOICE',    'Sales Invoice',     false, 'Issued customer invoice'),
  ('CUSTOMER_RECEIPT', 'Customer Receipt',  false, 'Payment received from a customer'),
  ('SALES_CREDIT_NOTE','Sales Credit Note', false, 'Credit note against a customer invoice')
on conflict (code) do nothing;

insert into app.document_types (code, name, description) values
  ('INV', 'Sales Invoice',     'Customer-facing invoice number'),
  ('RCT', 'Customer Receipt',  'Customer-facing receipt number'),
  ('SI',  'Sales Invoice JE',  'Journal generated by issuing an invoice'),
  ('CRP', 'Customer Receipt JE','Journal generated by posting a receipt')
on conflict (code) do nothing;

create or replace function gl.document_type_for_source(p_source_type text)
returns text
language sql
immutable
set search_path = pg_catalog, public
as $$
  select case p_source_type
    when 'MANUAL'            then 'JE'
    when 'OPENING_BALANCE'   then 'OB'
    when 'REVERSAL'          then 'REV'
    when 'FX_REVALUATION'    then 'FXR'
    when 'YEAR_END_CLOSE'    then 'YEC'
    when 'STOCK_MOVEMENT'    then 'STK'
    when 'SALES_INVOICE'     then 'SI'
    when 'CUSTOMER_RECEIPT'  then 'CRP'
    when 'SALES_CREDIT_NOTE' then 'SI'
    else 'JE'
  end;
$$;

-- ---------------------------------------------------------------------------
-- Documents
-- ---------------------------------------------------------------------------

create type sales.invoice_status as enum ('DRAFT', 'ISSUED', 'VOIDED');
create type sales.receipt_status as enum ('DRAFT', 'POSTED', 'REVERSED');

create table sales.invoices (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  invoice_no         text,
  status             sales.invoice_status not null default 'DRAFT',
  customer_id        uuid not null references app.customers (id) on delete restrict,
  invoice_date       date not null,
  due_date           date not null,
  currency_code      char(3) not null references app.currencies (code),
  payment_terms_id   uuid references app.payment_terms (id) on delete restrict,
  customer_po        text,
  notes              text,
  subtotal           app.money_amount not null default 0 check (subtotal >= 0),
  tax_total          app.money_amount not null default 0 check (tax_total >= 0),
  total              app.money_amount not null default 0 check (total >= 0),
  journal_entry_id   uuid references gl.journal_entry (id) on delete restrict,
  void_of_invoice_id uuid references sales.invoices (id) on delete restrict,
  void_reason        text,
  voided_at          timestamptz,
  voided_by          uuid references app.users (id),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  created_by         uuid,
  updated_by         uuid,
  unique (entity_id, invoice_no),
  constraint invoices_issued_has_number check (status = 'DRAFT' or invoice_no is not null),
  constraint invoices_issued_has_journal check (status <> 'ISSUED' or journal_entry_id is not null),
  constraint invoices_void_has_reason check (
    status <> 'VOIDED' or length(btrim(coalesce(void_reason, ''))) > 0
  ),
  constraint invoices_due_on_or_after_invoice check (due_date >= invoice_date)
);

comment on table sales.invoices is
  'Customer invoice. Drafts are ordinary rows. Issue and void go through sales.issue_invoice / sales.void_invoice, which are the only paths that write the ledger.';

create table sales.invoice_lines (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  invoice_id         uuid not null references sales.invoices (id) on delete cascade,
  line_no            integer not null check (line_no > 0),
  item_id            uuid references inv.items (id) on delete restrict,
  description        text not null check (length(btrim(description)) > 0),
  quantity           app.quantity not null check (quantity > 0),
  unit_price         app.money_amount not null check (unit_price >= 0),
  tax_code_id        uuid references app.tax_codes (id) on delete restrict,
  tax_amount         app.money_amount not null default 0 check (tax_amount >= 0),
  line_net           app.money_amount not null default 0 check (line_net >= 0),
  revenue_account_id uuid references gl.accounts (id) on delete restrict,
  created_at         timestamptz not null default now(),
  unique (invoice_id, line_no)
);

create table sales.receipts (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  receipt_no       text,
  status           sales.receipt_status not null default 'DRAFT',
  customer_id      uuid not null references app.customers (id) on delete restrict,
  receipt_date     date not null,
  currency_code    char(3) not null references app.currencies (code),
  amount           app.money_amount not null check (amount > 0),
  bank_account_id  uuid not null references gl.accounts (id) on delete restrict,
  memo             text,
  journal_entry_id uuid references gl.journal_entry (id) on delete restrict,
  reverse_reason   text,
  reversed_at      timestamptz,
  reversed_by      uuid references app.users (id),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, receipt_no),
  constraint receipts_posted_has_number check (status = 'DRAFT' or receipt_no is not null),
  constraint receipts_posted_has_journal check (status <> 'POSTED' or journal_entry_id is not null),
  constraint receipts_reversed_has_reason check (
    status <> 'REVERSED' or length(btrim(coalesce(reverse_reason, ''))) > 0
  )
);

create table sales.receipt_allocations (
  id          uuid primary key default gen_random_uuid(),
  entity_id   uuid not null references app.entities (id) on delete restrict,
  receipt_id  uuid not null references sales.receipts (id) on delete cascade,
  invoice_id  uuid not null references sales.invoices (id) on delete restrict,
  amount      app.money_amount not null check (amount > 0),
  created_at  timestamptz not null default now(),
  unique (receipt_id, invoice_id)
);

create index invoices_entity_status_idx on sales.invoices (entity_id, status, invoice_date desc);
create index invoices_customer_idx on sales.invoices (entity_id, customer_id, invoice_date desc);
create index invoice_lines_invoice_idx on sales.invoice_lines (invoice_id, line_no);
create index receipts_entity_status_idx on sales.receipts (entity_id, status, receipt_date desc);
create index receipts_customer_idx on sales.receipts (entity_id, customer_id, receipt_date desc);
create index receipt_allocations_invoice_idx on sales.receipt_allocations (invoice_id);

create or replace view sales.v_invoice_balances
with (security_invoker = true) as
select
  i.id,
  i.entity_id,
  i.total,
  coalesce((
    select sum(a.amount)
      from sales.receipt_allocations a
      join sales.receipts r on r.id = a.receipt_id
     where a.invoice_id = i.id
       and r.status = 'POSTED'
  ), 0) as allocated,
  i.total - coalesce((
    select sum(a.amount)
      from sales.receipt_allocations a
      join sales.receipts r on r.id = a.receipt_id
     where a.invoice_id = i.id
       and r.status = 'POSTED'
  ), 0) as outstanding
from sales.invoices i;

comment on view sales.v_invoice_balances is
  'Issued-invoice outstanding, after posted receipts only. Reversed receipts do not reduce the balance.';

-- ---------------------------------------------------------------------------
-- Mutation guards: drafts may be edited by the application role; issued
-- documents may be touched only from SECURITY DEFINER (current_user <> session_user).
-- ---------------------------------------------------------------------------

create or replace function sales.fn_guard_invoice()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'DRAFT' then
      raise exception 'An issued or voided invoice cannot be deleted'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if current_setting('sales.allow_status_change', true) is distinct from 'on' then
    if tg_op = 'UPDATE' and old.status <> 'DRAFT' then
      raise exception 'An issued invoice cannot be amended. Void it if it should not stand.'
        using errcode = 'restrict_violation';
    end if;
    if new.status is distinct from coalesce(old.status, 'DRAFT') then
      raise exception 'Change invoice status through sales.issue_invoice or sales.void_invoice'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger invoices_guard
  before insert or update or delete on sales.invoices
  for each row execute function sales.fn_guard_invoice();

create or replace function sales.fn_guard_invoice_line()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_status sales.invoice_status;
begin
  select status into v_status
    from sales.invoices
   where id = coalesce(new.invoice_id, old.invoice_id);

  if v_status <> 'DRAFT'
     and current_setting('sales.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on an issued invoice cannot be amended'
      using errcode = 'restrict_violation';
  end if;

  return coalesce(new, old);
end;
$$;

create trigger invoice_lines_guard
  before insert or update or delete on sales.invoice_lines
  for each row execute function sales.fn_guard_invoice_line();

create or replace function sales.fn_guard_receipt()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'DRAFT' then
      raise exception 'A posted receipt cannot be deleted. Reverse it.'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if current_setting('sales.allow_status_change', true) is distinct from 'on' then
    if tg_op = 'UPDATE' and old.status <> 'DRAFT' then
      raise exception 'A posted receipt cannot be amended. Reverse it.'
        using errcode = 'restrict_violation';
    end if;
    if new.status is distinct from coalesce(old.status, 'DRAFT') then
      raise exception 'Change receipt status through sales.post_receipt or sales.reverse_receipt'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger receipts_guard
  before insert or update or delete on sales.receipts
  for each row execute function sales.fn_guard_receipt();

select app.enable_updated_at('sales.invoices');
select app.enable_updated_at('sales.receipts');
select app.enable_audit('sales.invoices');
select app.enable_audit('sales.invoice_lines');
select app.enable_audit('sales.receipts');
select app.enable_audit('sales.receipt_allocations');

-- ---------------------------------------------------------------------------
-- Totals
-- ---------------------------------------------------------------------------

create or replace function sales.recompute_invoice_totals(p_invoice_id uuid)
returns void
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  update sales.invoices i
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select invoice_id,
             sum(line_net) as subtotal,
             sum(tax_amount) as tax_total
        from sales.invoice_lines
       where invoice_id = p_invoice_id
       group by invoice_id
    ) x
   where i.id = p_invoice_id
     and i.id = x.invoice_id;

  if not found then
    update sales.invoices
       set subtotal = 0, tax_total = 0, total = 0
     where id = p_invoice_id;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- Issue
-- ---------------------------------------------------------------------------

create or replace function sales.issue_invoice(
  p_invoice_id      uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_inv          sales.invoices%rowtype;
  v_customer     app.customers%rowtype;
  v_ar           uuid;
  v_entry_id     uuid;
  v_invoice_no   text;
  v_lines        jsonb := '[]'::jsonb;
  v_line         record;
  v_tax          record;
  v_revenue      uuid;
begin
  perform app.require_permission(
    (select entity_id from sales.invoices where id = p_invoice_id),
    'sales.invoice.issue'
  );

  select * into v_inv from sales.invoices where id = p_invoice_id for update;
  if not found then
    raise exception 'Invoice % does not exist', p_invoice_id using errcode = 'no_data_found';
  end if;
  if v_inv.status = 'ISSUED' then
    return v_inv.journal_entry_id;
  end if;
  if v_inv.status <> 'DRAFT' then
    raise exception 'Only a draft invoice can be issued' using errcode = 'restrict_violation';
  end if;

  perform sales.recompute_invoice_totals(v_inv.id);
  select * into v_inv from sales.invoices where id = v_inv.id;

  if v_inv.total <= 0 then
    raise exception 'An invoice needs at least one line with a positive amount'
      using errcode = 'check_violation';
  end if;

  select * into v_customer from app.customers where id = v_inv.customer_id;
  if not v_customer.is_active then
    raise exception 'Customer % is inactive', v_customer.code using errcode = 'restrict_violation';
  end if;
  if v_customer.is_credit_hold then
    raise exception 'Customer % is on credit hold: %', v_customer.code, v_customer.credit_hold_reason
      using errcode = 'restrict_violation';
  end if;
  if v_customer.entity_id <> v_inv.entity_id then
    raise exception 'Customer does not belong to this entity' using errcode = 'restrict_violation';
  end if;

  v_ar := coalesce(
    v_customer.ar_account_id,
    (select a.id from gl.accounts a
      where a.entity_id = v_inv.entity_id
        and a.control_type = 'ACCOUNTS_RECEIVABLE'
        and a.is_postable
      order by a.code
      limit 1)
  );
  if v_ar is null then
    raise exception 'No receivables control account is configured' using errcode = 'no_data_found';
  end if;

  for v_line in
    select l.*, t.rate as tax_rate, t.output_tax_account_id
      from sales.invoice_lines l
      left join app.tax_codes t on t.id = l.tax_code_id
     where l.invoice_id = v_inv.id
     order by l.line_no
  loop
    v_revenue := coalesce(
      v_line.revenue_account_id,
      (select i.revenue_account_id from inv.items i where i.id = v_line.item_id),
      gl.setting_account(v_inv.entity_id, 'DEFAULT_REVENUE')
    );

    v_lines := v_lines || jsonb_build_object(
      'account_id',    v_revenue,
      'currency_code', v_inv.currency_code,
      'credit',        v_line.line_net,
      'debit',         0,
      'memo',          v_line.description,
      'customer_id',   v_inv.customer_id,
      'item_id',       v_line.item_id
    );
  end loop;

  for v_tax in
    select t.output_tax_account_id as account_id, sum(l.tax_amount) as amount
      from sales.invoice_lines l
      join app.tax_codes t on t.id = l.tax_code_id
     where l.invoice_id = v_inv.id
       and l.tax_amount > 0
     group by t.output_tax_account_id
  loop
    if v_tax.account_id is null then
      raise exception 'Tax code is missing an output tax account' using errcode = 'no_data_found';
    end if;
    v_lines := v_lines || jsonb_build_object(
      'account_id',    v_tax.account_id,
      'currency_code', v_inv.currency_code,
      'credit',        v_tax.amount,
      'debit',         0,
      'memo',          'Output tax',
      'customer_id',   v_inv.customer_id
    );
  end loop;

  v_lines := v_lines || jsonb_build_object(
    'account_id',    v_ar,
    'currency_code', v_inv.currency_code,
    'debit',         v_inv.total,
    'credit',        0,
    'memo',          'Accounts receivable',
    'customer_id',   v_inv.customer_id
  );

  v_invoice_no := app.next_document_number(v_inv.entity_id, 'INV', v_inv.invoice_date);

  v_entry_id := gl.post_entry(
    v_inv.entity_id,
    jsonb_build_object(
      'entry_date',         v_inv.invoice_date,
      'source_type',        'SALES_INVOICE',
      'source_id',          v_inv.id,
      'source_document_no', v_invoice_no,
      'description',        'Invoice ' || v_invoice_no || ' · ' || v_customer.legal_name,
      'lines',              v_lines
    ),
    p_idempotency_key
  );

  perform set_config('sales.allow_status_change', 'on', true);

  update sales.invoices
     set status = 'ISSUED',
         invoice_no = v_invoice_no,
         journal_entry_id = v_entry_id
   where id = v_inv.id;

  perform set_config('sales.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

comment on function sales.issue_invoice(uuid, text) is
  'Issues a draft invoice: allocates INV-n, posts DR AR / CR revenue / CR output tax, and locks the document.';

-- ---------------------------------------------------------------------------
-- Void
-- ---------------------------------------------------------------------------

create or replace function sales.void_invoice(
  p_invoice_id uuid,
  p_reason     text
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_inv      sales.invoices%rowtype;
  v_entry_id uuid;
  v_reason   text := btrim(coalesce(p_reason, ''));
begin
  perform app.require_permission(
    (select entity_id from sales.invoices where id = p_invoice_id),
    'sales.invoice.void'
  );

  if length(v_reason) < 10 then
    raise exception 'A void needs a reason of at least ten characters'
      using errcode = 'check_violation';
  end if;

  select * into v_inv from sales.invoices where id = p_invoice_id for update;
  if not found then
    raise exception 'Invoice % does not exist', p_invoice_id using errcode = 'no_data_found';
  end if;
  if v_inv.status <> 'ISSUED' then
    raise exception 'Only an issued invoice can be voided' using errcode = 'restrict_violation';
  end if;

  if exists (
    select 1
      from sales.receipt_allocations a
      join sales.receipts r on r.id = a.receipt_id
     where a.invoice_id = v_inv.id
       and r.status = 'POSTED'
  ) then
    raise exception 'Invoice % has receipts applied. Reverse those first.'
      , v_inv.invoice_no
      using errcode = 'restrict_violation';
  end if;

  v_entry_id := gl.reverse_entry(v_inv.journal_entry_id, v_reason, null, null);

  perform set_config('sales.allow_status_change', 'on', true);

  update sales.invoices
     set status = 'VOIDED',
         void_reason = v_reason,
         voided_at = now(),
         voided_by = app.acting_user_id()
   where id = v_inv.id;

  perform set_config('sales.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Receipt
-- ---------------------------------------------------------------------------

create or replace function sales.post_receipt(
  p_receipt_id      uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_rct        sales.receipts%rowtype;
  v_customer   app.customers%rowtype;
  v_ar         uuid;
  v_bank       gl.accounts%rowtype;
  v_entry_id   uuid;
  v_receipt_no text;
  v_allocated  app.money_amount;
  v_open       app.money_amount;
  v_alloc      record;
begin
  perform app.require_permission(
    (select entity_id from sales.receipts where id = p_receipt_id),
    'sales.payment.create'
  );

  select * into v_rct from sales.receipts where id = p_receipt_id for update;
  if not found then
    raise exception 'Receipt % does not exist', p_receipt_id using errcode = 'no_data_found';
  end if;
  if v_rct.status = 'POSTED' then
    return v_rct.journal_entry_id;
  end if;
  if v_rct.status <> 'DRAFT' then
    raise exception 'Only a draft receipt can be posted' using errcode = 'restrict_violation';
  end if;

  select * into v_customer from app.customers where id = v_rct.customer_id;
  if v_customer.entity_id <> v_rct.entity_id then
    raise exception 'Customer does not belong to this entity' using errcode = 'restrict_violation';
  end if;

  select * into v_bank from gl.accounts where id = v_rct.bank_account_id;
  if not found or v_bank.entity_id <> v_rct.entity_id or not v_bank.is_postable then
    raise exception 'Bank account is not a postable account of this entity'
      using errcode = 'restrict_violation';
  end if;
  if v_bank.control_type is distinct from 'BANK' and v_bank.control_type is distinct from 'CASH' then
    raise exception 'Receipts must be deposited to a cash or bank account'
      using errcode = 'restrict_violation';
  end if;

  v_ar := coalesce(
    v_customer.ar_account_id,
    (select a.id from gl.accounts a
      where a.entity_id = v_rct.entity_id
        and a.control_type = 'ACCOUNTS_RECEIVABLE'
        and a.is_postable
      order by a.code
      limit 1)
  );

  select coalesce(sum(amount), 0) into v_allocated
    from sales.receipt_allocations
   where receipt_id = v_rct.id;

  if v_allocated > v_rct.amount then
    raise exception 'Allocations (%) exceed the receipt amount (%)', v_allocated, v_rct.amount
      using errcode = 'check_violation';
  end if;

  for v_alloc in
    select a.invoice_id, a.amount, i.invoice_no, i.status, i.customer_id, i.currency_code, b.outstanding
      from sales.receipt_allocations a
      join sales.invoices i on i.id = a.invoice_id
      join sales.v_invoice_balances b on b.id = i.id
     where a.receipt_id = v_rct.id
  loop
    if v_alloc.status <> 'ISSUED' then
      raise exception 'Receipts can only be applied to issued invoices'
        using errcode = 'restrict_violation';
    end if;
    if v_alloc.customer_id <> v_rct.customer_id then
      raise exception 'Invoice % belongs to a different customer', v_alloc.invoice_no
        using errcode = 'restrict_violation';
    end if;
    if v_alloc.currency_code <> v_rct.currency_code then
      raise exception 'Invoice % is in %; this receipt is in %',
        v_alloc.invoice_no, v_alloc.currency_code, v_rct.currency_code
        using errcode = 'check_violation';
    end if;
    if v_alloc.amount > v_alloc.outstanding then
      raise exception 'Allocation of % to invoice % exceeds the outstanding %',
        v_alloc.amount, v_alloc.invoice_no, v_alloc.outstanding
        using errcode = 'check_violation';
    end if;
  end loop;

  v_receipt_no := app.next_document_number(v_rct.entity_id, 'RCT', v_rct.receipt_date);

  v_entry_id := gl.post_entry(
    v_rct.entity_id,
    jsonb_build_object(
      'entry_date',         v_rct.receipt_date,
      'source_type',        'CUSTOMER_RECEIPT',
      'source_id',          v_rct.id,
      'source_document_no', v_receipt_no,
      'description',        'Receipt ' || v_receipt_no || ' · ' || v_customer.legal_name,
      'lines', jsonb_build_array(
        jsonb_build_object(
          'account_id',    v_rct.bank_account_id,
          'currency_code', v_rct.currency_code,
          'debit',         v_rct.amount,
          'credit',        0,
          'memo',          coalesce(v_rct.memo, 'Customer receipt'),
          'customer_id',   v_rct.customer_id
        ),
        jsonb_build_object(
          'account_id',    v_ar,
          'currency_code', v_rct.currency_code,
          'debit',         0,
          'credit',        v_rct.amount,
          'memo',          'Accounts receivable',
          'customer_id',   v_rct.customer_id
        )
      )
    ),
    p_idempotency_key
  );

  perform set_config('sales.allow_status_change', 'on', true);

  update sales.receipts
     set status = 'POSTED',
         receipt_no = v_receipt_no,
         journal_entry_id = v_entry_id
   where id = v_rct.id;

  perform set_config('sales.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

comment on function sales.post_receipt(uuid, text) is
  'Posts a draft receipt: DR cash/bank, CR AR. Allocations match open invoices and do not post again.';

create or replace function sales.reverse_receipt(
  p_receipt_id uuid,
  p_reason     text
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_rct      sales.receipts%rowtype;
  v_entry_id uuid;
  v_reason   text := btrim(coalesce(p_reason, ''));
begin
  perform app.require_permission(
    (select entity_id from sales.receipts where id = p_receipt_id),
    'sales.payment.reverse'
  );

  if length(v_reason) < 10 then
    raise exception 'A reversal needs a reason of at least ten characters'
      using errcode = 'check_violation';
  end if;

  select * into v_rct from sales.receipts where id = p_receipt_id for update;
  if not found then
    raise exception 'Receipt % does not exist', p_receipt_id using errcode = 'no_data_found';
  end if;
  if v_rct.status <> 'POSTED' then
    raise exception 'Only a posted receipt can be reversed' using errcode = 'restrict_violation';
  end if;

  v_entry_id := gl.reverse_entry(v_rct.journal_entry_id, v_reason, null, null);

  perform set_config('sales.allow_status_change', 'on', true);

  update sales.receipts
     set status = 'REVERSED',
         reverse_reason = v_reason,
         reversed_at = now(),
         reversed_by = app.acting_user_id()
   where id = v_rct.id;

  perform set_config('sales.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

create or replace function sales.save_invoice(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id         uuid := nullif(p_payload ->> 'invoice_id', '')::uuid;
  v_customer   uuid := (p_payload ->> 'customer_id')::uuid;
  v_date       date := (p_payload ->> 'invoice_date')::date;
  v_due        date;
  v_currency   char(3);
  v_terms      uuid := nullif(p_payload ->> 'payment_terms_id', '')::uuid;
  v_line       jsonb;
  v_line_no    integer := 0;
  v_qty        numeric;
  v_price      numeric;
  v_net        numeric;
  v_tax        numeric;
  v_rate       numeric;
  v_tax_id     uuid;
  v_status     sales.invoice_status;
begin
  perform app.require_permission(p_entity_id, 'sales.invoice.create');

  if v_customer is null or v_date is null then
    raise exception 'customer_id and invoice_date are required' using errcode = 'null_value_not_allowed';
  end if;

  if not exists (
    select 1 from app.customers c
     where c.id = v_customer and c.entity_id = p_entity_id
  ) then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer;

  if v_terms is not null then
    select (v_date + make_interval(days => t.days_net))::date into v_due
      from app.payment_terms t
     where t.id = v_terms and t.entity_id = p_entity_id;
  end if;
  v_due := coalesce((nullif(p_payload ->> 'due_date', ''))::date, v_due, v_date);

  if v_id is not null then
    select status into v_status from sales.invoices where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Invoice was not found' using errcode = 'no_data_found';
    end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft invoice can be saved' using errcode = 'restrict_violation';
    end if;

    update sales.invoices
       set customer_id = v_customer,
           invoice_date = v_date,
           due_date = v_due,
           currency_code = v_currency,
           payment_terms_id = v_terms,
           customer_po = nullif(p_payload ->> 'customer_po', ''),
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id;

    delete from sales.invoice_lines where invoice_id = v_id;
  else
    insert into sales.invoices (
      entity_id, customer_id, invoice_date, due_date, currency_code,
      payment_terms_id, customer_po, notes, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, v_due, v_currency,
      v_terms, nullif(p_payload ->> 'customer_po', ''), nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    )
    returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no
          using errcode = 'null_value_not_allowed';
      end if;

      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate
          from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);

      insert into sales.invoice_lines (
        entity_id, invoice_id, line_no, item_id, description,
        quantity, unit_price, tax_code_id, tax_amount, line_net, revenue_account_id
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'revenue_account_id', '')::uuid
      );
    end loop;
  end if;

  perform sales.recompute_invoice_totals(v_id);
  return v_id;
end;
$$;

create or replace function sales.save_receipt(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id       uuid := nullif(p_payload ->> 'receipt_id', '')::uuid;
  v_customer uuid := (p_payload ->> 'customer_id')::uuid;
  v_date     date := (p_payload ->> 'receipt_date')::date;
  v_amount   numeric := (p_payload ->> 'amount')::numeric;
  v_bank     uuid := (p_payload ->> 'bank_account_id')::uuid;
  v_currency char(3);
  v_status   sales.receipt_status;
  v_alloc    jsonb;
begin
  perform app.require_permission(p_entity_id, 'sales.payment.create');

  if v_customer is null or v_date is null or v_amount is null or v_bank is null then
    raise exception 'customer_id, receipt_date, amount and bank_account_id are required'
      using errcode = 'null_value_not_allowed';
  end if;
  if v_amount <= 0 then
    raise exception 'Receipt amount must be greater than zero' using errcode = 'check_violation';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer and c.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from sales.receipts where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Receipt was not found' using errcode = 'no_data_found';
    end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft receipt can be saved' using errcode = 'restrict_violation';
    end if;

    update sales.receipts
       set customer_id = v_customer,
           receipt_date = v_date,
           currency_code = v_currency,
           amount = v_amount,
           bank_account_id = v_bank,
           memo = nullif(p_payload ->> 'memo', ''),
           updated_by = app.acting_user_id()
     where id = v_id;

    delete from sales.receipt_allocations where receipt_id = v_id;
  else
    insert into sales.receipts (
      entity_id, customer_id, receipt_date, currency_code, amount,
      bank_account_id, memo, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, v_currency, v_amount,
      v_bank, nullif(p_payload ->> 'memo', ''),
      app.acting_user_id(), app.acting_user_id()
    )
    returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'allocations') = 'array' then
    for v_alloc in select * from jsonb_array_elements(p_payload -> 'allocations')
    loop
      insert into sales.receipt_allocations (entity_id, receipt_id, invoice_id, amount)
      values (
        p_entity_id,
        v_id,
        (v_alloc ->> 'invoice_id')::uuid,
        (v_alloc ->> 'amount')::numeric
      );
    end loop;
  end if;

  return v_id;
end;
$$;

create or replace function app.save_customer(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id       uuid := nullif(p_payload ->> 'customer_id', '')::uuid;
  v_code     text := btrim(coalesce(p_payload ->> 'code', ''));
  v_name     text := btrim(coalesce(p_payload ->> 'legal_name', ''));
  v_currency char(3);
begin
  perform app.require_permission(p_entity_id, 'masters.manage_customers');

  if v_name = '' then
    raise exception 'legal_name is required' using errcode = 'null_value_not_allowed';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), e.base_currency_code)
    into v_currency
    from app.entities e
   where e.id = p_entity_id;

  if v_code = '' then
    v_code := upper(left(regexp_replace(v_name, '[^A-Za-z0-9]+', '', 'g'), 8));
    if v_code = '' then
      v_code := 'CUST';
    end if;
    if exists (select 1 from app.customers where entity_id = p_entity_id and code = v_code) then
      v_code := v_code || '-' || substr(gen_random_uuid()::text, 1, 4);
    end if;
  end if;

  if v_id is not null then
    update app.customers
       set code = v_code,
           legal_name = v_name,
           trading_name = nullif(p_payload ->> 'trading_name', ''),
           tax_pin = nullif(p_payload ->> 'tax_pin', ''),
           currency_code = v_currency,
           payment_terms_id = nullif(p_payload ->> 'payment_terms_id', '')::uuid,
           email = nullif(p_payload ->> 'email', ''),
           phone = nullif(p_payload ->> 'phone', ''),
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Customer was not found' using errcode = 'no_data_found';
    end if;
    return v_id;
  end if;

  insert into app.customers (
    entity_id, code, legal_name, trading_name, tax_pin, currency_code,
    payment_terms_id, email, phone, notes, created_by, updated_by
  ) values (
    p_entity_id, v_code, v_name, nullif(p_payload ->> 'trading_name', ''),
    nullif(p_payload ->> 'tax_pin', ''), v_currency,
    nullif(p_payload ->> 'payment_terms_id', '')::uuid,
    nullif(p_payload ->> 'email', ''), nullif(p_payload ->> 'phone', ''),
    nullif(p_payload ->> 'notes', ''),
    app.acting_user_id(), app.acting_user_id()
  )
  returning id into v_id;

  return v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------

grant usage on schema sales to skyjet_app, authenticated;

grant select on all tables in schema sales to skyjet_app, authenticated;
grant select on sales.v_invoice_balances to skyjet_app, authenticated;
alter default privileges in schema sales grant select on tables to skyjet_app, authenticated;

grant execute on function
  sales.issue_invoice(uuid, text),
  sales.void_invoice(uuid, text),
  sales.post_receipt(uuid, text),
  sales.reverse_receipt(uuid, text),
  sales.recompute_invoice_totals(uuid),
  sales.save_invoice(uuid, jsonb),
  sales.save_receipt(uuid, jsonb),
  app.save_customer(uuid, jsonb)
to skyjet_app;

-- ---------------------------------------------------------------------------
-- RLS: sales joins the business schemas. No write policies — drafts and
-- posts go through SECURITY DEFINER functions, same as the ledger.
-- ---------------------------------------------------------------------------

create or replace function app.enforce_rls_everywhere()
returns integer
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_table record;
  v_count integer := 0;
begin
  for v_table in
    select n.nspname as schema_name, c.relname as table_name
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname in ('app', 'gl', 'inv', 'audit', 'integration', 'sales')
       and c.relkind = 'r'
       and not c.relrowsecurity
  loop
    execute format('alter table %I.%I enable row level security',
                   v_table.schema_name, v_table.table_name);
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

select app.enforce_rls_everywhere();

select app.apply_entity_read_policy(t) from (values
  ('sales.invoices'::regclass),
  ('sales.invoice_lines'::regclass),
  ('sales.receipts'::regclass),
  ('sales.receipt_allocations'::regclass)
) as tables(t);

create or replace view app.v_rls_coverage as
select
  n.nspname                                   as schema_name,
  c.relname                                   as table_name,
  c.relrowsecurity                            as rls_enabled,
  count(p.polname)::int                       as policy_count,
  count(p.polname) filter (
    where (select r.oid from pg_roles r where r.rolname = 'skyjet_app') = any (p.polroles)
  )::int                                      as app_role_policy_count,
  count(p.polname) filter (
    where (select r.oid from pg_roles r where r.rolname = 'authenticated') = any (p.polroles)
  )::int                                      as browser_policy_count
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
left join pg_policy p on p.polrelid = c.oid
where n.nspname in ('app', 'gl', 'inv', 'audit', 'integration', 'sales')
  and c.relkind = 'r'
group by n.nspname, c.relname, c.relrowsecurity
order by n.nspname, c.relname;

comment on view app.v_rls_coverage is
  'Every business table with its RLS state. rls_enabled false is a hole. policy_count zero denies everyone. app_role_policy_count zero means the application reads nothing from that table, which is almost always a mistake rather than a decision.';

create or replace view app.v_function_search_path as
select
  n.nspname as schema_name,
  p.proname as function_name,
  p.prosecdef as security_definer,
  exists (
    select 1 from unnest(coalesce(p.proconfig, '{}'::text[])) as c(setting)
     where c.setting like 'search\_path=%'
  ) as search_path_pinned
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname in ('app', 'gl', 'inv', 'integration', 'sales')
  and p.prokind in ('f', 'p');
