-- ===========================================================================
-- Purchasing payables cycle: POs, goods receipts, bills and supplier payments.
--
-- A purchase order is a commitment document only — it does not post the ledger.
-- Goods receipt posts inventory via inv.post_movement(RECEIPT) against GRNI.
-- The supplier bill clears GRNI (when matched to a GRN) or expenses the line,
-- books input VAT, and credits AP. Payments allocate against posted bills.
--
-- Permission mapping (existing catalogue codes; no new permissions here):
--   save_po / cancel draft PO     → procurement.purchase.create
--   approve_po                    → procurement.purchase.approve
--   save/post goods receipt       → procurement.purchase.receive
--   save/post bill                → finance.payment.create
--     (closest existing code; bills are AP documents, not bank payments —
--      finance.payment.create is reused until a dedicated AP bill permission
--      exists. Do not use procurement.purchase.receive for bill posting.)
--   save/post payment             → finance.payment.create
--   reverse_payment               → finance.payment.reverse
--   save/post credit              → finance.payment.create
-- ===========================================================================

set search_path = pg_catalog, public, extensions;

create schema if not exists purch;

comment on schema purch is
  'Supplier documents: purchase orders, goods receipts, bills, payments and credits. Inventory receipts go through inv.post_movement; AP and bank through gl.post_entry.';

-- ---------------------------------------------------------------------------
-- Catalogue: journal sources and document numbers
-- ---------------------------------------------------------------------------

insert into gl.journal_sources (code, name, is_manual, description) values
  ('PURCHASE_BILL',     'Purchase Bill',     false, 'Supplier bill / AP invoice'),
  ('SUPPLIER_PAYMENT',  'Supplier Payment',  false, 'Payment made to a supplier'),
  ('SUPPLIER_CREDIT',   'Supplier Credit',   false, 'Credit note from a supplier')
on conflict (code) do nothing;

insert into app.document_types (code, name, description) values
  ('PO',   'Purchase Order',       'Supplier-facing purchase order number'),
  ('GRN',  'Goods Receipt',        'Goods received note number'),
  ('BILL', 'Supplier Bill',        'Supplier-facing bill / AP invoice number'),
  ('SPAY', 'Supplier Payment',     'Supplier-facing payment number'),
  ('SCR',  'Supplier Credit',      'Supplier credit note number'),
  ('APB',  'Purchase Bill JE',     'Journal generated by posting a supplier bill'),
  ('SPY',  'Supplier Payment JE',  'Journal generated by posting a supplier payment'),
  ('SCJ',  'Supplier Credit JE',   'Journal generated by posting a supplier credit')
on conflict (code) do nothing;

create or replace function gl.document_type_for_source(p_source_type text)
returns text
language sql
immutable
set search_path = pg_catalog, public
as $$
  select case p_source_type
    when 'MANUAL'            then 'JE'
    when 'OPENING_BALANCE'   then 'OB'
    when 'REVERSAL'          then 'REV'
    when 'FX_REVALUATION'    then 'FXR'
    when 'YEAR_END_CLOSE'    then 'YEC'
    when 'STOCK_MOVEMENT'    then 'STK'
    when 'SALES_INVOICE'     then 'SI'
    when 'CUSTOMER_RECEIPT'  then 'CRP'
    when 'SALES_CREDIT_NOTE' then 'SI'
    when 'PURCHASE_BILL'     then 'APB'
    when 'SUPPLIER_PAYMENT'  then 'SPY'
    when 'SUPPLIER_CREDIT'   then 'SCJ'
    else 'JE'
  end;
$$;

-- ---------------------------------------------------------------------------
-- Status enums
-- ---------------------------------------------------------------------------

create type purch.po_status as enum ('DRAFT', 'APPROVED', 'CANCELLED');
create type purch.grn_status as enum ('DRAFT', 'POSTED');
create type purch.bill_status as enum ('DRAFT', 'POSTED', 'VOIDED');
create type purch.payment_status as enum ('DRAFT', 'POSTED', 'REVERSED');
create type purch.credit_status as enum ('DRAFT', 'POSTED');

-- ---------------------------------------------------------------------------
-- Documents
-- ---------------------------------------------------------------------------

create table purch.purchase_orders (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  po_no            text,
  status           purch.po_status not null default 'DRAFT',
  supplier_id      uuid not null references app.suppliers (id) on delete restrict,
  order_date       date not null,
  expected_date    date,
  currency_code    char(3) not null references app.currencies (code),
  payment_terms_id uuid references app.payment_terms (id) on delete restrict,
  warehouse_id     uuid references inv.warehouses (id) on delete restrict,
  notes            text,
  subtotal         app.money_amount not null default 0 check (subtotal >= 0),
  tax_total        app.money_amount not null default 0 check (tax_total >= 0),
  total            app.money_amount not null default 0 check (total >= 0),
  approved_at      timestamptz,
  approved_by      uuid references app.users (id),
  cancelled_at     timestamptz,
  cancelled_by     uuid references app.users (id),
  cancel_reason    text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, po_no),
  constraint purchase_orders_approved_has_number check (status = 'DRAFT' or status = 'CANCELLED' or po_no is not null),
  constraint purchase_orders_cancel_has_reason check (
    status <> 'CANCELLED' or length(btrim(coalesce(cancel_reason, ''))) > 0
  )
);

comment on table purch.purchase_orders is
  'Purchase commitment. Drafts are editable; approval allocates a number. Does not post the general ledger.';

create table purch.purchase_order_lines (
  id           uuid primary key default gen_random_uuid(),
  entity_id    uuid not null references app.entities (id) on delete restrict,
  po_id        uuid not null references purch.purchase_orders (id) on delete cascade,
  line_no      integer not null check (line_no > 0),
  item_id      uuid references inv.items (id) on delete restrict,
  description  text not null check (length(btrim(description)) > 0),
  quantity     app.quantity not null check (quantity > 0),
  unit_price   app.money_amount not null check (unit_price >= 0),
  tax_code_id  uuid references app.tax_codes (id) on delete restrict,
  tax_amount   app.money_amount not null default 0 check (tax_amount >= 0),
  line_net     app.money_amount not null default 0 check (line_net >= 0),
  created_at   timestamptz not null default now(),
  unique (po_id, line_no)
);

create table purch.goods_receipts (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  grn_no           text,
  status           purch.grn_status not null default 'DRAFT',
  supplier_id      uuid not null references app.suppliers (id) on delete restrict,
  po_id            uuid references purch.purchase_orders (id) on delete restrict,
  receipt_date     date not null,
  warehouse_id     uuid not null references inv.warehouses (id) on delete restrict,
  notes            text,
  posted_at        timestamptz,
  posted_by        uuid references app.users (id),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, grn_no),
  constraint goods_receipts_posted_has_number check (status = 'DRAFT' or grn_no is not null)
);

comment on table purch.goods_receipts is
  'Goods received note. Posting calls inv.post_movement(RECEIPT) per line (DR inventory / CR GRNI).';

create table purch.goods_receipt_lines (
  id                uuid primary key default gen_random_uuid(),
  entity_id         uuid not null references app.entities (id) on delete restrict,
  goods_receipt_id  uuid not null references purch.goods_receipts (id) on delete cascade,
  line_no           integer not null check (line_no > 0),
  po_line_id        uuid references purch.purchase_order_lines (id) on delete restrict,
  item_id           uuid not null references inv.items (id) on delete restrict,
  description       text not null check (length(btrim(description)) > 0),
  quantity          app.quantity not null check (quantity > 0),
  unit_cost         app.money_amount not null check (unit_cost >= 0),
  bin_id            uuid references inv.bins (id) on delete restrict,
  stock_unit_id     uuid references inv.stock_units (id) on delete restrict,
  serial_number     text,
  condition_code    text references inv.condition_codes (code) on delete restrict,
  stock_ledger_id   bigint references inv.stock_ledger (id) on delete restrict,
  created_at        timestamptz not null default now(),
  unique (goods_receipt_id, line_no)
);

comment on column purch.goods_receipt_lines.serial_number is
  'For SERIAL items: when stock_unit_id is null on post, a stock_unit is created from this serial then RECEIPTed.';
comment on column purch.goods_receipt_lines.unit_cost is
  'Required unit cost in base currency for inv.post_movement inbound valuation.';

create table purch.bills (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  bill_no          text,
  status           purch.bill_status not null default 'DRAFT',
  supplier_id      uuid not null references app.suppliers (id) on delete restrict,
  bill_date        date not null,
  due_date         date not null,
  currency_code    char(3) not null references app.currencies (code),
  payment_terms_id uuid references app.payment_terms (id) on delete restrict,
  supplier_ref     text,
  notes            text,
  subtotal         app.money_amount not null default 0 check (subtotal >= 0),
  tax_total        app.money_amount not null default 0 check (tax_total >= 0),
  total            app.money_amount not null default 0 check (total >= 0),
  journal_entry_id uuid references gl.journal_entry (id) on delete restrict,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, bill_no),
  constraint bills_posted_has_number check (status = 'DRAFT' or bill_no is not null),
  constraint bills_posted_has_journal check (status <> 'POSTED' or journal_entry_id is not null),
  constraint bills_due_on_or_after_bill check (due_date >= bill_date)
);

comment on table purch.bills is
  'Supplier bill. Matched GRN lines clear GRNI; unmatched lines debit expense (line account or DEFAULT_EXPENSE).';

create table purch.bill_lines (
  id                     uuid primary key default gen_random_uuid(),
  entity_id              uuid not null references app.entities (id) on delete restrict,
  bill_id                uuid not null references purch.bills (id) on delete cascade,
  line_no                integer not null check (line_no > 0),
  item_id                uuid references inv.items (id) on delete restrict,
  description            text not null check (length(btrim(description)) > 0),
  quantity               app.quantity not null check (quantity > 0),
  unit_price             app.money_amount not null check (unit_price >= 0),
  tax_code_id            uuid references app.tax_codes (id) on delete restrict,
  tax_amount             app.money_amount not null default 0 check (tax_amount >= 0),
  line_net               app.money_amount not null default 0 check (line_net >= 0),
  expense_account_id     uuid references gl.accounts (id) on delete restrict,
  goods_receipt_line_id  uuid references purch.goods_receipt_lines (id) on delete restrict,
  created_at             timestamptz not null default now(),
  unique (bill_id, line_no)
);

create table purch.bill_receipt_matches (
  id                uuid primary key default gen_random_uuid(),
  entity_id         uuid not null references app.entities (id) on delete restrict,
  bill_id           uuid not null references purch.bills (id) on delete cascade,
  goods_receipt_id  uuid not null references purch.goods_receipts (id) on delete restrict,
  amount            app.money_amount check (amount is null or amount > 0),
  created_at        timestamptz not null default now(),
  unique (bill_id, goods_receipt_id)
);

comment on table purch.bill_receipt_matches is
  'Optional header-level link from a bill to one or more goods receipts. Line-level clearing uses bill_lines.goods_receipt_line_id.';

create table purch.supplier_payments (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  payment_no       text,
  status           purch.payment_status not null default 'DRAFT',
  supplier_id      uuid not null references app.suppliers (id) on delete restrict,
  payment_date     date not null,
  currency_code    char(3) not null references app.currencies (code),
  amount           app.money_amount not null check (amount > 0),
  bank_account_id  uuid not null references gl.accounts (id) on delete restrict,
  memo             text,
  journal_entry_id uuid references gl.journal_entry (id) on delete restrict,
  reverse_reason   text,
  reversed_at      timestamptz,
  reversed_by      uuid references app.users (id),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, payment_no),
  constraint supplier_payments_posted_has_number check (status = 'DRAFT' or payment_no is not null),
  constraint supplier_payments_posted_has_journal check (status <> 'POSTED' or journal_entry_id is not null),
  constraint supplier_payments_reversed_has_reason check (
    status <> 'REVERSED' or length(btrim(coalesce(reverse_reason, ''))) > 0
  )
);

create table purch.supplier_payment_allocations (
  id          uuid primary key default gen_random_uuid(),
  entity_id   uuid not null references app.entities (id) on delete restrict,
  payment_id  uuid not null references purch.supplier_payments (id) on delete cascade,
  bill_id     uuid not null references purch.bills (id) on delete restrict,
  amount      app.money_amount not null check (amount > 0),
  created_at  timestamptz not null default now(),
  unique (payment_id, bill_id)
);

create table purch.supplier_credits (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  credit_no        text,
  status           purch.credit_status not null default 'DRAFT',
  supplier_id      uuid not null references app.suppliers (id) on delete restrict,
  credit_date      date not null,
  currency_code    char(3) not null references app.currencies (code),
  notes            text,
  subtotal         app.money_amount not null default 0 check (subtotal >= 0),
  tax_total        app.money_amount not null default 0 check (tax_total >= 0),
  total            app.money_amount not null default 0 check (total >= 0),
  journal_entry_id uuid references gl.journal_entry (id) on delete restrict,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, credit_no),
  constraint supplier_credits_posted_has_number check (status = 'DRAFT' or credit_no is not null),
  constraint supplier_credits_posted_has_journal check (status <> 'POSTED' or journal_entry_id is not null)
);

create table purch.supplier_credit_lines (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  credit_id          uuid not null references purch.supplier_credits (id) on delete cascade,
  line_no            integer not null check (line_no > 0),
  item_id            uuid references inv.items (id) on delete restrict,
  description        text not null check (length(btrim(description)) > 0),
  quantity           app.quantity not null check (quantity > 0),
  unit_price         app.money_amount not null check (unit_price >= 0),
  tax_code_id        uuid references app.tax_codes (id) on delete restrict,
  tax_amount         app.money_amount not null default 0 check (tax_amount >= 0),
  line_net           app.money_amount not null default 0 check (line_net >= 0),
  expense_account_id uuid references gl.accounts (id) on delete restrict,
  stock_unit_id      uuid references inv.stock_units (id) on delete restrict,
  warehouse_id       uuid references inv.warehouses (id) on delete restrict,
  created_at         timestamptz not null default now(),
  unique (credit_id, line_no)
);

create index purchase_orders_entity_status_idx
  on purch.purchase_orders (entity_id, status, order_date desc);
create index purchase_orders_supplier_idx
  on purch.purchase_orders (entity_id, supplier_id, order_date desc);
create index purchase_order_lines_po_idx on purch.purchase_order_lines (po_id, line_no);
create index goods_receipts_entity_status_idx
  on purch.goods_receipts (entity_id, status, receipt_date desc);
create index goods_receipt_lines_grn_idx on purch.goods_receipt_lines (goods_receipt_id, line_no);
create index bills_entity_status_idx on purch.bills (entity_id, status, bill_date desc);
create index bills_supplier_idx on purch.bills (entity_id, supplier_id, bill_date desc);
create index bill_lines_bill_idx on purch.bill_lines (bill_id, line_no);
create index supplier_payments_entity_status_idx
  on purch.supplier_payments (entity_id, status, payment_date desc);
create index supplier_payment_allocations_bill_idx
  on purch.supplier_payment_allocations (bill_id);
create index supplier_credits_entity_status_idx
  on purch.supplier_credits (entity_id, status, credit_date desc);

create or replace view purch.v_bill_balances
with (security_invoker = true) as
select
  b.id,
  b.entity_id,
  b.total,
  coalesce((
    select sum(a.amount)
      from purch.supplier_payment_allocations a
      join purch.supplier_payments p on p.id = a.payment_id
     where a.bill_id = b.id
       and p.status = 'POSTED'
  ), 0) as allocated,
  b.total - coalesce((
    select sum(a.amount)
      from purch.supplier_payment_allocations a
      join purch.supplier_payments p on p.id = a.payment_id
     where a.bill_id = b.id
       and p.status = 'POSTED'
  ), 0) as outstanding
from purch.bills b;

comment on view purch.v_bill_balances is
  'Posted-bill outstanding after posted supplier payments only. Reversed payments do not reduce the balance.';

-- ---------------------------------------------------------------------------
-- Mutation guards
-- ---------------------------------------------------------------------------

create or replace function purch.fn_guard_po()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'DRAFT' then
      raise exception 'An approved or cancelled purchase order cannot be deleted'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if current_setting('purch.allow_status_change', true) is distinct from 'on' then
    if tg_op = 'UPDATE' and old.status <> 'DRAFT' then
      raise exception 'An approved purchase order cannot be amended. Cancel it if it should not stand.'
        using errcode = 'restrict_violation';
    end if;
    if new.status is distinct from coalesce(old.status, 'DRAFT') then
      raise exception 'Change purchase order status through purch.approve_po or purch.cancel_po'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger purchase_orders_guard
  before insert or update or delete on purch.purchase_orders
  for each row execute function purch.fn_guard_po();

create or replace function purch.fn_guard_po_line()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_status purch.po_status;
begin
  select status into v_status
    from purch.purchase_orders
   where id = coalesce(new.po_id, old.po_id);

  if v_status <> 'DRAFT'
     and current_setting('purch.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on an approved purchase order cannot be amended'
      using errcode = 'restrict_violation';
  end if;

  return coalesce(new, old);
end;
$$;

create trigger purchase_order_lines_guard
  before insert or update or delete on purch.purchase_order_lines
  for each row execute function purch.fn_guard_po_line();

create or replace function purch.fn_guard_grn()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'DRAFT' then
      raise exception 'A posted goods receipt cannot be deleted'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if current_setting('purch.allow_status_change', true) is distinct from 'on' then
    if tg_op = 'UPDATE' and old.status <> 'DRAFT' then
      raise exception 'A posted goods receipt cannot be amended'
        using errcode = 'restrict_violation';
    end if;
    if new.status is distinct from coalesce(old.status, 'DRAFT') then
      raise exception 'Change goods receipt status through purch.post_goods_receipt'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger goods_receipts_guard
  before insert or update or delete on purch.goods_receipts
  for each row execute function purch.fn_guard_grn();

create or replace function purch.fn_guard_grn_line()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_status purch.grn_status;
begin
  select status into v_status
    from purch.goods_receipts
   where id = coalesce(new.goods_receipt_id, old.goods_receipt_id);

  if v_status <> 'DRAFT'
     and current_setting('purch.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on a posted goods receipt cannot be amended'
      using errcode = 'restrict_violation';
  end if;

  return coalesce(new, old);
end;
$$;

create trigger goods_receipt_lines_guard
  before insert or update or delete on purch.goods_receipt_lines
  for each row execute function purch.fn_guard_grn_line();

create or replace function purch.fn_guard_bill()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'DRAFT' then
      raise exception 'A posted bill cannot be deleted'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if current_setting('purch.allow_status_change', true) is distinct from 'on' then
    if tg_op = 'UPDATE' and old.status <> 'DRAFT' then
      raise exception 'A posted bill cannot be amended'
        using errcode = 'restrict_violation';
    end if;
    if new.status is distinct from coalesce(old.status, 'DRAFT') then
      raise exception 'Change bill status through purch.post_bill'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger bills_guard
  before insert or update or delete on purch.bills
  for each row execute function purch.fn_guard_bill();

create or replace function purch.fn_guard_bill_line()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_status purch.bill_status;
begin
  select status into v_status
    from purch.bills
   where id = coalesce(new.bill_id, old.bill_id);

  if v_status <> 'DRAFT'
     and current_setting('purch.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on a posted bill cannot be amended'
      using errcode = 'restrict_violation';
  end if;

  return coalesce(new, old);
end;
$$;

create trigger bill_lines_guard
  before insert or update or delete on purch.bill_lines
  for each row execute function purch.fn_guard_bill_line();

create or replace function purch.fn_guard_payment()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'DRAFT' then
      raise exception 'A posted payment cannot be deleted. Reverse it.'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if current_setting('purch.allow_status_change', true) is distinct from 'on' then
    if tg_op = 'UPDATE' and old.status <> 'DRAFT' then
      raise exception 'A posted payment cannot be amended. Reverse it.'
        using errcode = 'restrict_violation';
    end if;
    if new.status is distinct from coalesce(old.status, 'DRAFT') then
      raise exception 'Change payment status through purch.post_payment or purch.reverse_payment'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger supplier_payments_guard
  before insert or update or delete on purch.supplier_payments
  for each row execute function purch.fn_guard_payment();

create or replace function purch.fn_guard_credit()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'DRAFT' then
      raise exception 'A posted credit cannot be deleted'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if current_setting('purch.allow_status_change', true) is distinct from 'on' then
    if tg_op = 'UPDATE' and old.status <> 'DRAFT' then
      raise exception 'A posted credit cannot be amended'
        using errcode = 'restrict_violation';
    end if;
    if new.status is distinct from coalesce(old.status, 'DRAFT') then
      raise exception 'Change credit status through purch.post_credit'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger supplier_credits_guard
  before insert or update or delete on purch.supplier_credits
  for each row execute function purch.fn_guard_credit();

create or replace function purch.fn_guard_credit_line()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_status purch.credit_status;
begin
  select status into v_status
    from purch.supplier_credits
   where id = coalesce(new.credit_id, old.credit_id);

  if v_status <> 'DRAFT'
     and current_setting('purch.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on a posted credit cannot be amended'
      using errcode = 'restrict_violation';
  end if;

  return coalesce(new, old);
end;
$$;

create trigger supplier_credit_lines_guard
  before insert or update or delete on purch.supplier_credit_lines
  for each row execute function purch.fn_guard_credit_line();

select app.enable_updated_at('purch.purchase_orders');
select app.enable_updated_at('purch.goods_receipts');
select app.enable_updated_at('purch.bills');
select app.enable_updated_at('purch.supplier_payments');
select app.enable_updated_at('purch.supplier_credits');
select app.enable_audit('purch.purchase_orders');
select app.enable_audit('purch.purchase_order_lines');
select app.enable_audit('purch.goods_receipts');
select app.enable_audit('purch.goods_receipt_lines');
select app.enable_audit('purch.bills');
select app.enable_audit('purch.bill_lines');
select app.enable_audit('purch.bill_receipt_matches');
select app.enable_audit('purch.supplier_payments');
select app.enable_audit('purch.supplier_payment_allocations');
select app.enable_audit('purch.supplier_credits');
select app.enable_audit('purch.supplier_credit_lines');

-- ---------------------------------------------------------------------------
-- Totals helpers
-- ---------------------------------------------------------------------------

create or replace function purch.recompute_po_totals(p_po_id uuid)
returns void
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  update purch.purchase_orders po
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select po_id,
             sum(line_net) as subtotal,
             sum(tax_amount) as tax_total
        from purch.purchase_order_lines
       where po_id = p_po_id
       group by po_id
    ) x
   where po.id = p_po_id
     and po.id = x.po_id;

  if not found then
    update purch.purchase_orders
       set subtotal = 0, tax_total = 0, total = 0
     where id = p_po_id;
  end if;
end;
$$;

create or replace function purch.recompute_bill_totals(p_bill_id uuid)
returns void
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  update purch.bills b
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select bill_id,
             sum(line_net) as subtotal,
             sum(tax_amount) as tax_total
        from purch.bill_lines
       where bill_id = p_bill_id
       group by bill_id
    ) x
   where b.id = p_bill_id
     and b.id = x.bill_id;

  if not found then
    update purch.bills
       set subtotal = 0, tax_total = 0, total = 0
     where id = p_bill_id;
  end if;
end;
$$;

create or replace function purch.recompute_credit_totals(p_credit_id uuid)
returns void
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  update purch.supplier_credits c
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select credit_id,
             sum(line_net) as subtotal,
             sum(tax_amount) as tax_total
        from purch.supplier_credit_lines
       where credit_id = p_credit_id
       group by credit_id
    ) x
   where c.id = p_credit_id
     and c.id = x.credit_id;

  if not found then
    update purch.supplier_credits
       set subtotal = 0, tax_total = 0, total = 0
     where id = p_credit_id;
  end if;
end;
$$;

create or replace function purch.resolve_expense_account(
  p_entity_id uuid,
  p_override  uuid
)
returns uuid
language plpgsql
stable
set search_path = pg_catalog, public
as $$
declare
  v_id uuid;
begin
  if p_override is not null then
    return p_override;
  end if;

  select account_id into v_id
    from gl.entity_account_settings
   where entity_id = p_entity_id
     and setting_code = 'DEFAULT_EXPENSE';

  if v_id is null then
    raise exception 'Expense account is required on the line, or configure DEFAULT_EXPENSE for the entity'
      using errcode = 'no_data_found';
  end if;

  return v_id;
end;
$$;

create or replace function purch.ap_account(p_entity_id uuid, p_supplier_id uuid)
returns uuid
language plpgsql
stable
set search_path = pg_catalog, public
as $$
declare
  v_ap uuid;
begin
  select coalesce(
           s.ap_account_id,
           (select a.id from gl.accounts a
             where a.entity_id = p_entity_id
               and a.control_type = 'ACCOUNTS_PAYABLE'
               and a.is_postable
             order by a.code
             limit 1)
         )
    into v_ap
    from app.suppliers s
   where s.id = p_supplier_id
     and s.entity_id = p_entity_id;

  if v_ap is null then
    raise exception 'No payables control account is configured' using errcode = 'no_data_found';
  end if;

  return v_ap;
end;
$$;

-- ---------------------------------------------------------------------------
-- Purchase orders
-- ---------------------------------------------------------------------------

create or replace function purch.save_po(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id         uuid := nullif(p_payload ->> 'po_id', '')::uuid;
  v_supplier   uuid := (p_payload ->> 'supplier_id')::uuid;
  v_date       date := (p_payload ->> 'order_date')::date;
  v_currency   char(3);
  v_terms      uuid := nullif(p_payload ->> 'payment_terms_id', '')::uuid;
  v_warehouse  uuid := nullif(p_payload ->> 'warehouse_id', '')::uuid;
  v_line       jsonb;
  v_line_no    integer := 0;
  v_qty        numeric;
  v_price      numeric;
  v_net        numeric;
  v_tax        numeric;
  v_rate       numeric;
  v_tax_id     uuid;
  v_status     purch.po_status;
begin
  -- Permission: procurement.purchase.create
  perform app.require_permission(p_entity_id, 'procurement.purchase.create');

  if v_supplier is null or v_date is null then
    raise exception 'supplier_id and order_date are required' using errcode = 'null_value_not_allowed';
  end if;

  if not exists (
    select 1 from app.suppliers s
     where s.id = v_supplier and s.entity_id = p_entity_id and s.is_active
  ) then
    raise exception 'Supplier was not found in this entity' using errcode = 'no_data_found';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), s.currency_code)
    into v_currency
    from app.suppliers s
   where s.id = v_supplier;

  if v_id is not null then
    select status into v_status from purch.purchase_orders where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Purchase order was not found' using errcode = 'no_data_found';
    end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft purchase order can be saved' using errcode = 'restrict_violation';
    end if;

    update purch.purchase_orders
       set supplier_id = v_supplier,
           order_date = v_date,
           expected_date = nullif(p_payload ->> 'expected_date', '')::date,
           currency_code = v_currency,
           payment_terms_id = v_terms,
           warehouse_id = v_warehouse,
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id;

    delete from purch.purchase_order_lines where po_id = v_id;
  else
    insert into purch.purchase_orders (
      entity_id, supplier_id, order_date, expected_date, currency_code,
      payment_terms_id, warehouse_id, notes, created_by, updated_by
    ) values (
      p_entity_id, v_supplier, v_date, nullif(p_payload ->> 'expected_date', '')::date, v_currency,
      v_terms, v_warehouse, nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    )
    returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no
          using errcode = 'null_value_not_allowed';
      end if;

      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate
          from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);

      insert into purch.purchase_order_lines (
        entity_id, po_id, line_no, item_id, description,
        quantity, unit_price, tax_code_id, tax_amount, line_net
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        v_qty, v_price, v_tax_id, v_tax, v_net
      );
    end loop;
  end if;

  perform purch.recompute_po_totals(v_id);
  return v_id;
end;
$$;

comment on function purch.save_po(uuid, jsonb) is
  'Creates or updates a draft purchase order. Requires procurement.purchase.create.';

create or replace function purch.approve_po(p_po_id uuid)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_po       purch.purchase_orders%rowtype;
  v_supplier app.suppliers%rowtype;
  v_po_no    text;
begin
  -- Permission: procurement.purchase.approve
  perform app.require_permission(
    (select entity_id from purch.purchase_orders where id = p_po_id),
    'procurement.purchase.approve'
  );

  select * into v_po from purch.purchase_orders where id = p_po_id for update;
  if not found then
    raise exception 'Purchase order % does not exist', p_po_id using errcode = 'no_data_found';
  end if;
  if v_po.status = 'APPROVED' then
    return v_po.po_no;
  end if;
  if v_po.status <> 'DRAFT' then
    raise exception 'Only a draft purchase order can be approved' using errcode = 'restrict_violation';
  end if;

  perform purch.recompute_po_totals(v_po.id);
  select * into v_po from purch.purchase_orders where id = v_po.id;

  if not exists (select 1 from purch.purchase_order_lines where po_id = v_po.id) then
    raise exception 'A purchase order needs at least one line' using errcode = 'check_violation';
  end if;

  select * into v_supplier from app.suppliers where id = v_po.supplier_id;
  if not v_supplier.is_active then
    raise exception 'Supplier % is inactive', v_supplier.code using errcode = 'restrict_violation';
  end if;
  if v_supplier.approval_status <> 'APPROVED' then
    raise exception 'Supplier % is not approved for purchasing (%)',
      v_supplier.code, v_supplier.approval_status
      using errcode = 'restrict_violation';
  end if;
  if v_supplier.approval_expires_on is not null
     and v_supplier.approval_expires_on < v_po.order_date then
    raise exception 'Supplier % approval expired on %',
      v_supplier.code, v_supplier.approval_expires_on
      using errcode = 'restrict_violation';
  end if;
  if v_supplier.entity_id <> v_po.entity_id then
    raise exception 'Supplier does not belong to this entity' using errcode = 'restrict_violation';
  end if;

  v_po_no := app.next_document_number(v_po.entity_id, 'PO', v_po.order_date);

  perform set_config('purch.allow_status_change', 'on', true);

  update purch.purchase_orders
     set status = 'APPROVED',
         po_no = v_po_no,
         approved_at = now(),
         approved_by = app.acting_user_id()
   where id = v_po.id;

  perform set_config('purch.allow_status_change', '', true);

  return v_po_no;
end;
$$;

comment on function purch.approve_po(uuid) is
  'Approves a draft PO and allocates PO-n. Does not post GL. Requires procurement.purchase.approve.';

create or replace function purch.cancel_po(p_po_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_po     purch.purchase_orders%rowtype;
  v_reason text := btrim(coalesce(p_reason, ''));
begin
  -- Permission: procurement.purchase.create (draft cancel only)
  perform app.require_permission(
    (select entity_id from purch.purchase_orders where id = p_po_id),
    'procurement.purchase.create'
  );

  if length(v_reason) < 5 then
    raise exception 'A cancel needs a reason of at least five characters'
      using errcode = 'check_violation';
  end if;

  select * into v_po from purch.purchase_orders where id = p_po_id for update;
  if not found then
    raise exception 'Purchase order % does not exist', p_po_id using errcode = 'no_data_found';
  end if;
  if v_po.status <> 'DRAFT' then
    raise exception 'Only a draft purchase order can be cancelled' using errcode = 'restrict_violation';
  end if;

  perform set_config('purch.allow_status_change', 'on', true);

  update purch.purchase_orders
     set status = 'CANCELLED',
         cancel_reason = v_reason,
         cancelled_at = now(),
         cancelled_by = app.acting_user_id()
   where id = v_po.id;

  perform set_config('purch.allow_status_change', '', true);
end;
$$;

comment on function purch.cancel_po(uuid, text) is
  'Cancels a draft purchase order. Requires procurement.purchase.create.';

-- ---------------------------------------------------------------------------
-- Goods receipts
-- ---------------------------------------------------------------------------

create or replace function purch.save_goods_receipt(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id         uuid := nullif(p_payload ->> 'goods_receipt_id', '')::uuid;
  v_supplier   uuid := (p_payload ->> 'supplier_id')::uuid;
  v_po         uuid := nullif(p_payload ->> 'po_id', '')::uuid;
  v_date       date := (p_payload ->> 'receipt_date')::date;
  v_warehouse  uuid := (p_payload ->> 'warehouse_id')::uuid;
  v_line       jsonb;
  v_line_no    integer := 0;
  v_status     purch.grn_status;
  v_po_row     purch.purchase_orders%rowtype;
begin
  -- Permission: procurement.purchase.receive
  perform app.require_permission(p_entity_id, 'procurement.purchase.receive');

  if v_date is null or v_warehouse is null then
    raise exception 'receipt_date and warehouse_id are required' using errcode = 'null_value_not_allowed';
  end if;

  if not exists (
    select 1 from inv.warehouses w
     where w.id = v_warehouse and w.entity_id = p_entity_id and w.is_active
  ) then
    raise exception 'Warehouse was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_po is not null then
    select * into v_po_row from purch.purchase_orders where id = v_po and entity_id = p_entity_id;
    if not found then
      raise exception 'Purchase order was not found' using errcode = 'no_data_found';
    end if;
    if v_po_row.status <> 'APPROVED' then
      raise exception 'Goods can only be received against an approved purchase order'
        using errcode = 'restrict_violation';
    end if;
    v_supplier := coalesce(v_supplier, v_po_row.supplier_id);
  end if;

  if v_supplier is null then
    raise exception 'supplier_id is required' using errcode = 'null_value_not_allowed';
  end if;

  if not exists (
    select 1 from app.suppliers s
     where s.id = v_supplier and s.entity_id = p_entity_id
  ) then
    raise exception 'Supplier was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from purch.goods_receipts where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Goods receipt was not found' using errcode = 'no_data_found';
    end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft goods receipt can be saved' using errcode = 'restrict_violation';
    end if;

    update purch.goods_receipts
       set supplier_id = v_supplier,
           po_id = v_po,
           receipt_date = v_date,
           warehouse_id = v_warehouse,
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id;

    delete from purch.goods_receipt_lines where goods_receipt_id = v_id;
  else
    insert into purch.goods_receipts (
      entity_id, supplier_id, po_id, receipt_date, warehouse_id, notes, created_by, updated_by
    ) values (
      p_entity_id, v_supplier, v_po, v_date, v_warehouse,
      nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    )
    returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      if nullif(v_line ->> 'item_id', '') is null then
        raise exception 'Line %: item_id is required', v_line_no using errcode = 'null_value_not_allowed';
      end if;
      if (v_line ->> 'quantity')::numeric is null or (v_line ->> 'quantity')::numeric <= 0 then
        raise exception 'Line %: quantity must be positive', v_line_no using errcode = 'check_violation';
      end if;
      if (v_line ->> 'unit_cost')::numeric is null or (v_line ->> 'unit_cost')::numeric < 0 then
        raise exception 'Line %: unit_cost is required and must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no using errcode = 'null_value_not_allowed';
      end if;

      insert into purch.goods_receipt_lines (
        entity_id, goods_receipt_id, line_no, po_line_id, item_id, description,
        quantity, unit_cost, bin_id, stock_unit_id, serial_number, condition_code
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'po_line_id', '')::uuid,
        (v_line ->> 'item_id')::uuid,
        btrim(v_line ->> 'description'),
        (v_line ->> 'quantity')::numeric,
        (v_line ->> 'unit_cost')::numeric,
        nullif(v_line ->> 'bin_id', '')::uuid,
        nullif(v_line ->> 'stock_unit_id', '')::uuid,
        nullif(btrim(coalesce(v_line ->> 'serial_number', '')), ''),
        coalesce(nullif(v_line ->> 'condition_code', ''), 'OH')
      );
    end loop;
  end if;

  return v_id;
end;
$$;

create or replace function purch.post_goods_receipt(
  p_grn_id          uuid,
  p_idempotency_key text default null
)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_grn        purch.goods_receipts%rowtype;
  v_line       purch.goods_receipt_lines%rowtype;
  v_item       inv.items%rowtype;
  v_bin        uuid;
  v_unit       uuid;
  v_ledger_id  bigint;
  v_grn_no     text;
  v_key        text;
begin
  -- Permission: procurement.purchase.receive
  perform app.require_permission(
    (select entity_id from purch.goods_receipts where id = p_grn_id),
    'procurement.purchase.receive'
  );

  select * into v_grn from purch.goods_receipts where id = p_grn_id for update;
  if not found then
    raise exception 'Goods receipt % does not exist', p_grn_id using errcode = 'no_data_found';
  end if;
  if v_grn.status = 'POSTED' then
    return v_grn.grn_no;
  end if;
  if v_grn.status <> 'DRAFT' then
    raise exception 'Only a draft goods receipt can be posted' using errcode = 'restrict_violation';
  end if;

  if not exists (select 1 from purch.goods_receipt_lines where goods_receipt_id = v_grn.id) then
    raise exception 'A goods receipt needs at least one line' using errcode = 'check_violation';
  end if;

  v_grn_no := app.next_document_number(v_grn.entity_id, 'GRN', v_grn.receipt_date);

  for v_line in
    select * from purch.goods_receipt_lines
     where goods_receipt_id = v_grn.id
     order by line_no
  loop
    select * into v_item from inv.items where id = v_line.item_id and entity_id = v_grn.entity_id;
    if not found then
      raise exception 'Line %: item was not found', v_line.line_no using errcode = 'no_data_found';
    end if;

    v_bin := v_line.bin_id;
    if v_bin is null then
      select id into v_bin
        from inv.bins
       where warehouse_id = v_grn.warehouse_id
         and code = 'MAIN'
         and is_active
       limit 1;
    end if;

    v_unit := v_line.stock_unit_id;

    if v_item.tracking_mode = 'SERIAL' then
      if v_line.quantity <> 1 then
        raise exception 'Line %: serialised receipts are one unit at a time', v_line.line_no
          using errcode = 'check_violation';
      end if;

      if v_unit is null then
        if length(btrim(coalesce(v_line.serial_number, ''))) = 0 then
          raise exception 'Line %: serial_number is required for a serialised item', v_line.line_no
            using errcode = 'null_value_not_allowed';
        end if;
        if v_bin is null then
          raise exception 'Line %: a bin is required to create a stock unit', v_line.line_no
            using errcode = 'null_value_not_allowed';
        end if;

        insert into inv.stock_units (
          entity_id, item_id, serial_number, condition_code, status,
          warehouse_id, bin_id, supplier_id, received_date,
          acquisition_currency, acquisition_cost, unit_cost_base, created_by
        ) values (
          v_grn.entity_id, v_line.item_id, v_line.serial_number,
          coalesce(v_line.condition_code, 'OH'), 'ON_HAND',
          v_grn.warehouse_id, v_bin, v_grn.supplier_id, v_grn.receipt_date,
          (select base_currency_code from app.entities where id = v_grn.entity_id),
          v_line.unit_cost, v_line.unit_cost, app.acting_user_id()
        )
        returning id into v_unit;

        update purch.goods_receipt_lines
           set stock_unit_id = v_unit
         where id = v_line.id;
      end if;
    end if;

    v_key := case
      when p_idempotency_key is not null then p_idempotency_key || ':grn-line:' || v_line.line_no
      else null
    end;

    v_ledger_id := inv.post_movement(
      p_entity_id => v_grn.entity_id,
      p_item_id => v_line.item_id,
      p_warehouse_id => v_grn.warehouse_id,
      p_movement_type => 'RECEIPT',
      p_movement_date => v_grn.receipt_date,
      p_quantity => v_line.quantity,
      p_bin_id => v_bin,
      p_stock_unit_id => v_unit,
      p_unit_cost_base => v_line.unit_cost,
      p_source_type => 'GOODS_RECEIPT',
      p_source_id => v_grn.id,
      p_source_line_id => v_line.id,
      p_reference => v_grn_no,
      p_notes => v_line.description,
      p_idempotency_key => v_key
    );

    update purch.goods_receipt_lines
       set stock_ledger_id = v_ledger_id,
           bin_id = coalesce(bin_id, v_bin)
     where id = v_line.id;
  end loop;

  perform set_config('purch.allow_status_change', 'on', true);

  update purch.goods_receipts
     set status = 'POSTED',
         grn_no = v_grn_no,
         posted_at = now(),
         posted_by = app.acting_user_id()
   where id = v_grn.id;

  perform set_config('purch.allow_status_change', '', true);

  return v_grn_no;
end;
$$;

comment on function purch.post_goods_receipt(uuid, text) is
  'Posts a GRN: creates stock units for serials when needed, then inv.post_movement(RECEIPT). Requires procurement.purchase.receive.';

-- ---------------------------------------------------------------------------
-- Bills
-- ---------------------------------------------------------------------------

create or replace function purch.save_bill(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id         uuid := nullif(p_payload ->> 'bill_id', '')::uuid;
  v_supplier   uuid := (p_payload ->> 'supplier_id')::uuid;
  v_date       date := (p_payload ->> 'bill_date')::date;
  v_due        date;
  v_currency   char(3);
  v_terms      uuid := nullif(p_payload ->> 'payment_terms_id', '')::uuid;
  v_line       jsonb;
  v_match      jsonb;
  v_line_no    integer := 0;
  v_qty        numeric;
  v_price      numeric;
  v_net        numeric;
  v_tax        numeric;
  v_rate       numeric;
  v_tax_id     uuid;
  v_status     purch.bill_status;
begin
  -- Permission: finance.payment.create (closest existing; see migration header)
  perform app.require_permission(p_entity_id, 'finance.payment.create');

  if v_supplier is null or v_date is null then
    raise exception 'supplier_id and bill_date are required' using errcode = 'null_value_not_allowed';
  end if;

  if not exists (
    select 1 from app.suppliers s
     where s.id = v_supplier and s.entity_id = p_entity_id
  ) then
    raise exception 'Supplier was not found in this entity' using errcode = 'no_data_found';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), s.currency_code)
    into v_currency
    from app.suppliers s
   where s.id = v_supplier;

  if v_terms is not null then
    select (v_date + make_interval(days => t.days_net))::date into v_due
      from app.payment_terms t
     where t.id = v_terms and t.entity_id = p_entity_id;
  end if;
  v_due := coalesce((nullif(p_payload ->> 'due_date', ''))::date, v_due, v_date);

  if v_id is not null then
    select status into v_status from purch.bills where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Bill was not found' using errcode = 'no_data_found';
    end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft bill can be saved' using errcode = 'restrict_violation';
    end if;

    update purch.bills
       set supplier_id = v_supplier,
           bill_date = v_date,
           due_date = v_due,
           currency_code = v_currency,
           payment_terms_id = v_terms,
           supplier_ref = nullif(p_payload ->> 'supplier_ref', ''),
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id;

    delete from purch.bill_lines where bill_id = v_id;
    delete from purch.bill_receipt_matches where bill_id = v_id;
  else
    insert into purch.bills (
      entity_id, supplier_id, bill_date, due_date, currency_code,
      payment_terms_id, supplier_ref, notes, created_by, updated_by
    ) values (
      p_entity_id, v_supplier, v_date, v_due, v_currency,
      v_terms, nullif(p_payload ->> 'supplier_ref', ''), nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    )
    returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no
          using errcode = 'null_value_not_allowed';
      end if;

      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate
          from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);

      insert into purch.bill_lines (
        entity_id, bill_id, line_no, item_id, description,
        quantity, unit_price, tax_code_id, tax_amount, line_net,
        expense_account_id, goods_receipt_line_id
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'expense_account_id', '')::uuid,
        nullif(v_line ->> 'goods_receipt_line_id', '')::uuid
      );
    end loop;
  end if;

  if jsonb_typeof(p_payload -> 'receipt_matches') = 'array' then
    for v_match in select * from jsonb_array_elements(p_payload -> 'receipt_matches')
    loop
      insert into purch.bill_receipt_matches (
        entity_id, bill_id, goods_receipt_id, amount
      ) values (
        p_entity_id,
        v_id,
        (v_match ->> 'goods_receipt_id')::uuid,
        nullif(v_match ->> 'amount', '')::numeric
      );
    end loop;
  end if;

  perform purch.recompute_bill_totals(v_id);
  return v_id;
end;
$$;

create or replace function purch.post_bill(
  p_bill_id         uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_bill       purch.bills%rowtype;
  v_supplier   app.suppliers%rowtype;
  v_ap         uuid;
  v_grni       uuid;
  v_entry_id   uuid;
  v_bill_no    text;
  v_lines      jsonb := '[]'::jsonb;
  v_line       record;
  v_tax        record;
  v_debit_acct uuid;
  v_grn_line   purch.goods_receipt_lines%rowtype;
  v_grn        purch.goods_receipts%rowtype;
begin
  -- Permission: finance.payment.create (AP bill post; see migration header)
  perform app.require_permission(
    (select entity_id from purch.bills where id = p_bill_id),
    'finance.payment.create'
  );

  select * into v_bill from purch.bills where id = p_bill_id for update;
  if not found then
    raise exception 'Bill % does not exist', p_bill_id using errcode = 'no_data_found';
  end if;
  if v_bill.status = 'POSTED' then
    return v_bill.journal_entry_id;
  end if;
  if v_bill.status <> 'DRAFT' then
    raise exception 'Only a draft bill can be posted' using errcode = 'restrict_violation';
  end if;

  perform purch.recompute_bill_totals(v_bill.id);
  select * into v_bill from purch.bills where id = v_bill.id;

  if v_bill.total <= 0 then
    raise exception 'A bill needs at least one line with a positive amount'
      using errcode = 'check_violation';
  end if;

  select * into v_supplier from app.suppliers where id = v_bill.supplier_id;
  if v_supplier.entity_id <> v_bill.entity_id then
    raise exception 'Supplier does not belong to this entity' using errcode = 'restrict_violation';
  end if;

  v_ap := purch.ap_account(v_bill.entity_id, v_bill.supplier_id);
  v_grni := gl.setting_account(v_bill.entity_id, 'GOODS_RECEIVED_NOT_INVOICED');

  for v_line in
    select l.*, t.input_tax_account_id
      from purch.bill_lines l
      left join app.tax_codes t on t.id = l.tax_code_id
     where l.bill_id = v_bill.id
     order by l.line_no
  loop
    if v_line.goods_receipt_line_id is not null then
      select * into v_grn_line from purch.goods_receipt_lines where id = v_line.goods_receipt_line_id;
      if not found then
        raise exception 'Line %: goods receipt line was not found', v_line.line_no
          using errcode = 'no_data_found';
      end if;
      select * into v_grn from purch.goods_receipts where id = v_grn_line.goods_receipt_id;
      if v_grn.status <> 'POSTED' then
        raise exception 'Line %: goods receipt must be posted before matching', v_line.line_no
          using errcode = 'restrict_violation';
      end if;
      if v_grn.supplier_id <> v_bill.supplier_id then
        raise exception 'Line %: goods receipt belongs to a different supplier', v_line.line_no
          using errcode = 'restrict_violation';
      end if;
      v_debit_acct := v_grni;
    else
      v_debit_acct := purch.resolve_expense_account(v_bill.entity_id, v_line.expense_account_id);
    end if;

    v_lines := v_lines || jsonb_build_object(
      'account_id',    v_debit_acct,
      'currency_code', v_bill.currency_code,
      'debit',         v_line.line_net,
      'credit',        0,
      'memo',          v_line.description,
      'supplier_id',   v_bill.supplier_id,
      'item_id',       v_line.item_id
    );
  end loop;

  for v_tax in
    select t.input_tax_account_id as account_id, sum(l.tax_amount) as amount
      from purch.bill_lines l
      join app.tax_codes t on t.id = l.tax_code_id
     where l.bill_id = v_bill.id
       and l.tax_amount > 0
     group by t.input_tax_account_id
  loop
    if v_tax.account_id is null then
      raise exception 'Tax code is missing an input tax account' using errcode = 'no_data_found';
    end if;
    v_lines := v_lines || jsonb_build_object(
      'account_id',    v_tax.account_id,
      'currency_code', v_bill.currency_code,
      'debit',         v_tax.amount,
      'credit',        0,
      'memo',          'Input tax',
      'supplier_id',   v_bill.supplier_id
    );
  end loop;

  v_lines := v_lines || jsonb_build_object(
    'account_id',    v_ap,
    'currency_code', v_bill.currency_code,
    'debit',         0,
    'credit',        v_bill.total,
    'memo',          'Accounts payable',
    'supplier_id',   v_bill.supplier_id
  );

  v_bill_no := app.next_document_number(v_bill.entity_id, 'BILL', v_bill.bill_date);

  v_entry_id := gl.post_entry(
    v_bill.entity_id,
    jsonb_build_object(
      'entry_date',         v_bill.bill_date,
      'source_type',        'PURCHASE_BILL',
      'source_id',          v_bill.id,
      'source_document_no', v_bill_no,
      'description',        'Bill ' || v_bill_no || ' · ' || v_supplier.legal_name,
      'lines',              v_lines
    ),
    p_idempotency_key
  );

  perform set_config('purch.allow_status_change', 'on', true);

  update purch.bills
     set status = 'POSTED',
         bill_no = v_bill_no,
         journal_entry_id = v_entry_id
   where id = v_bill.id;

  perform set_config('purch.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

comment on function purch.post_bill(uuid, text) is
  'Posts a supplier bill: DR GRNI or expense, DR VAT input, CR AP. Requires finance.payment.create.';

-- ---------------------------------------------------------------------------
-- Supplier payments
-- ---------------------------------------------------------------------------

create or replace function purch.save_payment(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id       uuid := nullif(p_payload ->> 'payment_id', '')::uuid;
  v_supplier uuid := (p_payload ->> 'supplier_id')::uuid;
  v_date     date := (p_payload ->> 'payment_date')::date;
  v_amount   numeric := (p_payload ->> 'amount')::numeric;
  v_bank     uuid := (p_payload ->> 'bank_account_id')::uuid;
  v_currency char(3);
  v_status   purch.payment_status;
  v_alloc    jsonb;
begin
  -- Permission: finance.payment.create
  perform app.require_permission(p_entity_id, 'finance.payment.create');

  if v_supplier is null or v_date is null or v_amount is null or v_bank is null then
    raise exception 'supplier_id, payment_date, amount and bank_account_id are required'
      using errcode = 'null_value_not_allowed';
  end if;
  if v_amount <= 0 then
    raise exception 'Payment amount must be greater than zero' using errcode = 'check_violation';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), s.currency_code)
    into v_currency
    from app.suppliers s
   where s.id = v_supplier and s.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Supplier was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from purch.supplier_payments where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Payment was not found' using errcode = 'no_data_found';
    end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft payment can be saved' using errcode = 'restrict_violation';
    end if;

    update purch.supplier_payments
       set supplier_id = v_supplier,
           payment_date = v_date,
           currency_code = v_currency,
           amount = v_amount,
           bank_account_id = v_bank,
           memo = nullif(p_payload ->> 'memo', ''),
           updated_by = app.acting_user_id()
     where id = v_id;

    delete from purch.supplier_payment_allocations where payment_id = v_id;
  else
    insert into purch.supplier_payments (
      entity_id, supplier_id, payment_date, currency_code, amount,
      bank_account_id, memo, created_by, updated_by
    ) values (
      p_entity_id, v_supplier, v_date, v_currency, v_amount,
      v_bank, nullif(p_payload ->> 'memo', ''),
      app.acting_user_id(), app.acting_user_id()
    )
    returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'allocations') = 'array' then
    for v_alloc in select * from jsonb_array_elements(p_payload -> 'allocations')
    loop
      insert into purch.supplier_payment_allocations (entity_id, payment_id, bill_id, amount)
      values (
        p_entity_id,
        v_id,
        (v_alloc ->> 'bill_id')::uuid,
        (v_alloc ->> 'amount')::numeric
      );
    end loop;
  end if;

  return v_id;
end;
$$;

create or replace function purch.post_payment(
  p_payment_id      uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_pay        purch.supplier_payments%rowtype;
  v_supplier   app.suppliers%rowtype;
  v_ap         uuid;
  v_bank       gl.accounts%rowtype;
  v_entry_id   uuid;
  v_payment_no text;
  v_allocated  app.money_amount;
  v_alloc      record;
begin
  -- Permission: finance.payment.create
  perform app.require_permission(
    (select entity_id from purch.supplier_payments where id = p_payment_id),
    'finance.payment.create'
  );

  select * into v_pay from purch.supplier_payments where id = p_payment_id for update;
  if not found then
    raise exception 'Payment % does not exist', p_payment_id using errcode = 'no_data_found';
  end if;
  if v_pay.status = 'POSTED' then
    return v_pay.journal_entry_id;
  end if;
  if v_pay.status <> 'DRAFT' then
    raise exception 'Only a draft payment can be posted' using errcode = 'restrict_violation';
  end if;

  select * into v_supplier from app.suppliers where id = v_pay.supplier_id;
  if v_supplier.entity_id <> v_pay.entity_id then
    raise exception 'Supplier does not belong to this entity' using errcode = 'restrict_violation';
  end if;

  select * into v_bank from gl.accounts where id = v_pay.bank_account_id;
  if not found or v_bank.entity_id <> v_pay.entity_id or not v_bank.is_postable then
    raise exception 'Bank account is not a postable account of this entity'
      using errcode = 'restrict_violation';
  end if;
  if v_bank.control_type is distinct from 'BANK' and v_bank.control_type is distinct from 'CASH' then
    raise exception 'Payments must be drawn from a cash or bank account'
      using errcode = 'restrict_violation';
  end if;

  v_ap := purch.ap_account(v_pay.entity_id, v_pay.supplier_id);

  select coalesce(sum(amount), 0) into v_allocated
    from purch.supplier_payment_allocations
   where payment_id = v_pay.id;

  if v_allocated > v_pay.amount then
    raise exception 'Allocations (%) exceed the payment amount (%)', v_allocated, v_pay.amount
      using errcode = 'check_violation';
  end if;

  for v_alloc in
    select a.bill_id, a.amount, b.bill_no, b.status, b.supplier_id, b.currency_code, bal.outstanding
      from purch.supplier_payment_allocations a
      join purch.bills b on b.id = a.bill_id
      join purch.v_bill_balances bal on bal.id = b.id
     where a.payment_id = v_pay.id
  loop
    if v_alloc.status <> 'POSTED' then
      raise exception 'Payments can only be applied to posted bills'
        using errcode = 'restrict_violation';
    end if;
    if v_alloc.supplier_id <> v_pay.supplier_id then
      raise exception 'Bill % belongs to a different supplier', v_alloc.bill_no
        using errcode = 'restrict_violation';
    end if;
    if v_alloc.currency_code <> v_pay.currency_code then
      raise exception 'Bill % is in %; this payment is in %',
        v_alloc.bill_no, v_alloc.currency_code, v_pay.currency_code
        using errcode = 'check_violation';
    end if;
    if v_alloc.amount > v_alloc.outstanding then
      raise exception 'Allocation of % to bill % exceeds the outstanding %',
        v_alloc.amount, v_alloc.bill_no, v_alloc.outstanding
        using errcode = 'check_violation';
    end if;
  end loop;

  v_payment_no := app.next_document_number(v_pay.entity_id, 'SPAY', v_pay.payment_date);

  v_entry_id := gl.post_entry(
    v_pay.entity_id,
    jsonb_build_object(
      'entry_date',         v_pay.payment_date,
      'source_type',        'SUPPLIER_PAYMENT',
      'source_id',          v_pay.id,
      'source_document_no', v_payment_no,
      'description',        'Payment ' || v_payment_no || ' · ' || v_supplier.legal_name,
      'lines', jsonb_build_array(
        jsonb_build_object(
          'account_id',    v_ap,
          'currency_code', v_pay.currency_code,
          'debit',         v_pay.amount,
          'credit',        0,
          'memo',          'Accounts payable',
          'supplier_id',   v_pay.supplier_id
        ),
        jsonb_build_object(
          'account_id',    v_pay.bank_account_id,
          'currency_code', v_pay.currency_code,
          'debit',         0,
          'credit',        v_pay.amount,
          'memo',          coalesce(v_pay.memo, 'Supplier payment'),
          'supplier_id',   v_pay.supplier_id
        )
      )
    ),
    p_idempotency_key
  );

  perform set_config('purch.allow_status_change', 'on', true);

  update purch.supplier_payments
     set status = 'POSTED',
         payment_no = v_payment_no,
         journal_entry_id = v_entry_id
   where id = v_pay.id;

  perform set_config('purch.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

comment on function purch.post_payment(uuid, text) is
  'Posts a supplier payment: DR AP, CR cash/bank. Allocations match open bills. Requires finance.payment.create.';

create or replace function purch.reverse_payment(
  p_payment_id uuid,
  p_reason     text
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_pay      purch.supplier_payments%rowtype;
  v_entry_id uuid;
  v_reason   text := btrim(coalesce(p_reason, ''));
begin
  -- Permission: finance.payment.reverse
  perform app.require_permission(
    (select entity_id from purch.supplier_payments where id = p_payment_id),
    'finance.payment.reverse'
  );

  if length(v_reason) < 10 then
    raise exception 'A reversal needs a reason of at least ten characters'
      using errcode = 'check_violation';
  end if;

  select * into v_pay from purch.supplier_payments where id = p_payment_id for update;
  if not found then
    raise exception 'Payment % does not exist', p_payment_id using errcode = 'no_data_found';
  end if;
  if v_pay.status <> 'POSTED' then
    raise exception 'Only a posted payment can be reversed' using errcode = 'restrict_violation';
  end if;

  v_entry_id := gl.reverse_entry(v_pay.journal_entry_id, v_reason, null, null);

  perform set_config('purch.allow_status_change', 'on', true);

  update purch.supplier_payments
     set status = 'REVERSED',
         reverse_reason = v_reason,
         reversed_at = now(),
         reversed_by = app.acting_user_id()
   where id = v_pay.id;

  perform set_config('purch.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Supplier credits
-- ---------------------------------------------------------------------------

create or replace function purch.save_credit(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id         uuid := nullif(p_payload ->> 'credit_id', '')::uuid;
  v_supplier   uuid := (p_payload ->> 'supplier_id')::uuid;
  v_date       date := (p_payload ->> 'credit_date')::date;
  v_currency   char(3);
  v_line       jsonb;
  v_line_no    integer := 0;
  v_qty        numeric;
  v_price      numeric;
  v_net        numeric;
  v_tax        numeric;
  v_rate       numeric;
  v_tax_id     uuid;
  v_status     purch.credit_status;
begin
  -- Permission: finance.payment.create
  perform app.require_permission(p_entity_id, 'finance.payment.create');

  if v_supplier is null or v_date is null then
    raise exception 'supplier_id and credit_date are required' using errcode = 'null_value_not_allowed';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), s.currency_code)
    into v_currency
    from app.suppliers s
   where s.id = v_supplier and s.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Supplier was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from purch.supplier_credits where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Credit was not found' using errcode = 'no_data_found';
    end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft credit can be saved' using errcode = 'restrict_violation';
    end if;

    update purch.supplier_credits
       set supplier_id = v_supplier,
           credit_date = v_date,
           currency_code = v_currency,
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id;

    delete from purch.supplier_credit_lines where credit_id = v_id;
  else
    insert into purch.supplier_credits (
      entity_id, supplier_id, credit_date, currency_code, notes, created_by, updated_by
    ) values (
      p_entity_id, v_supplier, v_date, v_currency,
      nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    )
    returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no
          using errcode = 'null_value_not_allowed';
      end if;

      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate
          from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);

      insert into purch.supplier_credit_lines (
        entity_id, credit_id, line_no, item_id, description,
        quantity, unit_price, tax_code_id, tax_amount, line_net,
        expense_account_id, stock_unit_id, warehouse_id
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'expense_account_id', '')::uuid,
        nullif(v_line ->> 'stock_unit_id', '')::uuid,
        nullif(v_line ->> 'warehouse_id', '')::uuid
      );
    end loop;
  end if;

  perform purch.recompute_credit_totals(v_id);
  return v_id;
end;
$$;

create or replace function purch.post_credit(
  p_credit_id       uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_credit     purch.supplier_credits%rowtype;
  v_supplier   app.suppliers%rowtype;
  v_ap         uuid;
  v_entry_id   uuid;
  v_credit_no  text;
  v_lines      jsonb := '[]'::jsonb;
  v_line       record;
  v_tax        record;
  v_credit_acct uuid;
  v_key        text;
begin
  -- Permission: finance.payment.create
  perform app.require_permission(
    (select entity_id from purch.supplier_credits where id = p_credit_id),
    'finance.payment.create'
  );

  select * into v_credit from purch.supplier_credits where id = p_credit_id for update;
  if not found then
    raise exception 'Credit % does not exist', p_credit_id using errcode = 'no_data_found';
  end if;
  if v_credit.status = 'POSTED' then
    return v_credit.journal_entry_id;
  end if;
  if v_credit.status <> 'DRAFT' then
    raise exception 'Only a draft credit can be posted' using errcode = 'restrict_violation';
  end if;

  perform purch.recompute_credit_totals(v_credit.id);
  select * into v_credit from purch.supplier_credits where id = v_credit.id;

  if v_credit.total <= 0 then
    raise exception 'A credit needs at least one line with a positive amount'
      using errcode = 'check_violation';
  end if;

  select * into v_supplier from app.suppliers where id = v_credit.supplier_id;
  v_ap := purch.ap_account(v_credit.entity_id, v_credit.supplier_id);

  -- Inventory returns first (SUPPLIER_RETURN undoes RECEIPT valuation against GRNI).
  for v_line in
    select * from purch.supplier_credit_lines
     where credit_id = v_credit.id
       and stock_unit_id is not null
     order by line_no
  loop
    if v_line.warehouse_id is null or v_line.item_id is null then
      raise exception 'Line %: inventory return needs item_id and warehouse_id', v_line.line_no
        using errcode = 'null_value_not_allowed';
    end if;
    if v_line.quantity <> 1 then
      raise exception 'Line %: serialised returns are one unit at a time', v_line.line_no
        using errcode = 'check_violation';
    end if;

    v_key := case
      when p_idempotency_key is not null then p_idempotency_key || ':return:' || v_line.line_no
      else null
    end;

    perform inv.post_movement(
      p_entity_id => v_credit.entity_id,
      p_item_id => v_line.item_id,
      p_warehouse_id => v_line.warehouse_id,
      p_movement_type => 'SUPPLIER_RETURN',
      p_movement_date => v_credit.credit_date,
      p_quantity => -v_line.quantity,
      p_stock_unit_id => v_line.stock_unit_id,
      p_source_type => 'SUPPLIER_CREDIT',
      p_source_id => v_credit.id,
      p_source_line_id => v_line.id,
      p_reference => null,
      p_notes => v_line.description,
      p_idempotency_key => v_key
    );
  end loop;

  -- AP reduction journal: DR AP; CR expense (or GRNI for inventory-return lines); CR input tax.
  v_lines := v_lines || jsonb_build_object(
    'account_id',    v_ap,
    'currency_code', v_credit.currency_code,
    'debit',         v_credit.total,
    'credit',        0,
    'memo',          'Accounts payable',
    'supplier_id',   v_credit.supplier_id
  );

  for v_line in
    select l.*
      from purch.supplier_credit_lines l
     where l.credit_id = v_credit.id
     order by l.line_no
  loop
    if v_line.stock_unit_id is not null then
      v_credit_acct := gl.setting_account(v_credit.entity_id, 'GOODS_RECEIVED_NOT_INVOICED');
    else
      v_credit_acct := purch.resolve_expense_account(v_credit.entity_id, v_line.expense_account_id);
    end if;

    v_lines := v_lines || jsonb_build_object(
      'account_id',    v_credit_acct,
      'currency_code', v_credit.currency_code,
      'debit',         0,
      'credit',        v_line.line_net,
      'memo',          v_line.description,
      'supplier_id',   v_credit.supplier_id,
      'item_id',       v_line.item_id,
      'stock_unit_id', v_line.stock_unit_id
    );
  end loop;

  for v_tax in
    select t.input_tax_account_id as account_id, sum(l.tax_amount) as amount
      from purch.supplier_credit_lines l
      join app.tax_codes t on t.id = l.tax_code_id
     where l.credit_id = v_credit.id
       and l.tax_amount > 0
     group by t.input_tax_account_id
  loop
    if v_tax.account_id is null then
      raise exception 'Tax code is missing an input tax account' using errcode = 'no_data_found';
    end if;
    v_lines := v_lines || jsonb_build_object(
      'account_id',    v_tax.account_id,
      'currency_code', v_credit.currency_code,
      'debit',         0,
      'credit',        v_tax.amount,
      'memo',          'Input tax reversal',
      'supplier_id',   v_credit.supplier_id
    );
  end loop;

  v_credit_no := app.next_document_number(v_credit.entity_id, 'SCR', v_credit.credit_date);

  v_entry_id := gl.post_entry(
    v_credit.entity_id,
    jsonb_build_object(
      'entry_date',         v_credit.credit_date,
      'source_type',        'SUPPLIER_CREDIT',
      'source_id',          v_credit.id,
      'source_document_no', v_credit_no,
      'description',        'Credit ' || v_credit_no || ' · ' || v_supplier.legal_name,
      'lines',              v_lines
    ),
    p_idempotency_key
  );

  perform set_config('purch.allow_status_change', 'on', true);

  update purch.supplier_credits
     set status = 'POSTED',
         credit_no = v_credit_no,
         journal_entry_id = v_entry_id
   where id = v_credit.id;

  perform set_config('purch.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

comment on function purch.post_credit(uuid, text) is
  'Posts a supplier credit: DR AP / CR expense (or GRNI after SUPPLIER_RETURN). Requires finance.payment.create.';

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------

grant usage on schema purch to skyjet_app, authenticated;

grant select on all tables in schema purch to skyjet_app, authenticated;
grant select on purch.v_bill_balances to skyjet_app, authenticated;
alter default privileges in schema purch grant select on tables to skyjet_app, authenticated;

grant execute on function
  purch.save_po(uuid, jsonb),
  purch.approve_po(uuid),
  purch.cancel_po(uuid, text),
  purch.save_goods_receipt(uuid, jsonb),
  purch.post_goods_receipt(uuid, text),
  purch.save_bill(uuid, jsonb),
  purch.post_bill(uuid, text),
  purch.save_payment(uuid, jsonb),
  purch.post_payment(uuid, text),
  purch.reverse_payment(uuid, text),
  purch.save_credit(uuid, jsonb),
  purch.post_credit(uuid, text),
  purch.recompute_po_totals(uuid),
  purch.recompute_bill_totals(uuid),
  purch.recompute_credit_totals(uuid),
  purch.resolve_expense_account(uuid, uuid),
  purch.ap_account(uuid, uuid)
to skyjet_app;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

create or replace function app.enforce_rls_everywhere()
returns integer
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_table record;
  v_count integer := 0;
begin
  for v_table in
    select n.nspname as schema_name, c.relname as table_name
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname in ('app', 'gl', 'inv', 'audit', 'integration', 'sales', 'purch')
       and c.relkind = 'r'
       and not c.relrowsecurity
  loop
    execute format('alter table %I.%I enable row level security',
                   v_table.schema_name, v_table.table_name);
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

select app.enforce_rls_everywhere();

select app.apply_entity_read_policy(t) from (values
  ('purch.purchase_orders'::regclass),
  ('purch.purchase_order_lines'::regclass),
  ('purch.goods_receipts'::regclass),
  ('purch.goods_receipt_lines'::regclass),
  ('purch.bills'::regclass),
  ('purch.bill_lines'::regclass),
  ('purch.bill_receipt_matches'::regclass),
  ('purch.supplier_payments'::regclass),
  ('purch.supplier_payment_allocations'::regclass),
  ('purch.supplier_credits'::regclass),
  ('purch.supplier_credit_lines'::regclass)
) as tables(t);

create or replace view app.v_rls_coverage as
select
  n.nspname                                   as schema_name,
  c.relname                                   as table_name,
  c.relrowsecurity                            as rls_enabled,
  count(p.polname)::int                       as policy_count,
  count(p.polname) filter (
    where (select r.oid from pg_roles r where r.rolname = 'skyjet_app') = any (p.polroles)
  )::int                                      as app_role_policy_count,
  count(p.polname) filter (
    where (select r.oid from pg_roles r where r.rolname = 'authenticated') = any (p.polroles)
  )::int                                      as browser_policy_count
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
left join pg_policy p on p.polrelid = c.oid
where n.nspname in ('app', 'gl', 'inv', 'audit', 'integration', 'sales', 'purch')
  and c.relkind = 'r'
group by n.nspname, c.relname, c.relrowsecurity
order by n.nspname, c.relname;

create or replace view app.v_function_search_path as
select
  n.nspname as schema_name,
  p.proname as function_name,
  p.prosecdef as security_definer,
  exists (
    select 1 from unnest(coalesce(p.proconfig, '{}'::text[])) as c(setting)
     where c.setting like 'search\_path=%'
  ) as search_path_pinned
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname in ('app', 'gl', 'inv', 'integration', 'sales', 'purch')
  and p.prokind in ('f', 'p');
