-- ===========================================================================
-- Sales documents: quotations, orders, credit/debit notes, refunds, statements.
--
-- Quotations and sales orders are commercial documents only — no GL.
-- Credit notes reverse AR / revenue / output tax (mirror of invoice issue).
-- Debit notes increase AR simply. Refunds pay money out (reverse of receipt).
--
-- Permissions (reuse existing catalogue):
--   save/send/accept/cancel quote, convert   → sales.invoice.create / issue
--   save/confirm/cancel order, convert       → sales.invoice.create / issue
--   save/post credit or debit note           → sales.invoice.create / issue
--   save/post refund                         → sales.payment.create
-- ===========================================================================

set search_path = pg_catalog, public, extensions;

insert into gl.journal_sources (code, name, is_manual, description) values
  ('SALES_DEBIT_NOTE', 'Sales Debit Note', false, 'Debit note increasing customer AR'),
  ('CUSTOMER_REFUND',  'Customer Refund',  false, 'Refund paid to a customer')
on conflict (code) do nothing;

insert into app.document_types (code, name, description) values
  ('QT',  'Sales Quotation',      'Customer-facing quotation / estimate number'),
  ('SO',  'Sales Order',          'Customer-facing sales order number'),
  ('CN',  'Sales Credit Note',    'Customer-facing credit note number'),
  ('DN',  'Sales Debit Note',     'Customer-facing debit note number'),
  ('RF',  'Customer Refund',      'Customer-facing refund number'),
  ('SDN', 'Sales Debit Note JE',  'Journal generated by posting a debit note'),
  ('CRF', 'Customer Refund JE',   'Journal generated by posting a refund')
on conflict (code) do nothing;

create or replace function gl.document_type_for_source(p_source_type text)
returns text
language sql
immutable
set search_path = pg_catalog, public
as $$
  select case p_source_type
    when 'MANUAL'            then 'JE'
    when 'OPENING_BALANCE'   then 'OB'
    when 'REVERSAL'          then 'REV'
    when 'FX_REVALUATION'    then 'FXR'
    when 'YEAR_END_CLOSE'    then 'YEC'
    when 'STOCK_MOVEMENT'    then 'STK'
    when 'SALES_INVOICE'     then 'SI'
    when 'CUSTOMER_RECEIPT'  then 'CRP'
    when 'SALES_CREDIT_NOTE' then 'SI'
    when 'SALES_DEBIT_NOTE'  then 'SDN'
    when 'CUSTOMER_REFUND'   then 'CRF'
    when 'PURCHASE_BILL'     then 'APB'
    when 'SUPPLIER_PAYMENT'  then 'SPY'
    when 'SUPPLIER_CREDIT'   then 'SCJ'
    else 'JE'
  end;
$$;

-- ---------------------------------------------------------------------------
-- Status enums
-- ---------------------------------------------------------------------------

create type sales.quotation_status as enum ('DRAFT', 'SENT', 'ACCEPTED', 'CANCELLED');
create type sales.sales_order_status as enum ('DRAFT', 'CONFIRMED', 'CANCELLED');
create type sales.credit_note_status as enum ('DRAFT', 'POSTED');
create type sales.debit_note_status as enum ('DRAFT', 'POSTED');
create type sales.refund_status as enum ('DRAFT', 'POSTED', 'REVERSED');

-- ---------------------------------------------------------------------------
-- Quotations
-- ---------------------------------------------------------------------------

create table sales.quotations (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  quotation_no     text,
  status           sales.quotation_status not null default 'DRAFT',
  customer_id      uuid not null references app.customers (id) on delete restrict,
  quotation_date   date not null,
  valid_until      date,
  currency_code    char(3) not null references app.currencies (code),
  payment_terms_id uuid references app.payment_terms (id) on delete restrict,
  warehouse_id     uuid references inv.warehouses (id) on delete restrict,
  notes            text,
  subtotal         app.money_amount not null default 0 check (subtotal >= 0),
  tax_total        app.money_amount not null default 0 check (tax_total >= 0),
  total            app.money_amount not null default 0 check (total >= 0),
  converted_invoice_id uuid references sales.invoices (id) on delete restrict,
  cancelled_at     timestamptz,
  cancelled_by     uuid references app.users (id),
  cancel_reason    text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, quotation_no),
  constraint quotations_non_draft_has_number check (
    status = 'DRAFT' or status = 'CANCELLED' or quotation_no is not null
  ),
  constraint quotations_cancel_has_reason check (
    status <> 'CANCELLED' or length(btrim(coalesce(cancel_reason, ''))) > 0
  )
);

comment on table sales.quotations is
  'Customer estimate / quotation. No GL. Convert to invoice via sales.convert_quotation_to_invoice.';

create table sales.quotation_lines (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  quotation_id       uuid not null references sales.quotations (id) on delete cascade,
  line_no            integer not null check (line_no > 0),
  item_id            uuid references inv.items (id) on delete restrict,
  description        text not null check (length(btrim(description)) > 0),
  quantity           app.quantity not null check (quantity > 0),
  unit_price         app.money_amount not null check (unit_price >= 0),
  tax_code_id        uuid references app.tax_codes (id) on delete restrict,
  tax_amount         app.money_amount not null default 0 check (tax_amount >= 0),
  line_net           app.money_amount not null default 0 check (line_net >= 0),
  revenue_account_id uuid references gl.accounts (id) on delete restrict,
  created_at         timestamptz not null default now(),
  unique (quotation_id, line_no)
);

-- ---------------------------------------------------------------------------
-- Sales orders
-- ---------------------------------------------------------------------------

create table sales.sales_orders (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  order_no         text,
  status           sales.sales_order_status not null default 'DRAFT',
  customer_id      uuid not null references app.customers (id) on delete restrict,
  order_date       date not null,
  currency_code    char(3) not null references app.currencies (code),
  payment_terms_id uuid references app.payment_terms (id) on delete restrict,
  warehouse_id     uuid references inv.warehouses (id) on delete restrict,
  customer_po      text,
  notes            text,
  quotation_id     uuid references sales.quotations (id) on delete restrict,
  subtotal         app.money_amount not null default 0 check (subtotal >= 0),
  tax_total        app.money_amount not null default 0 check (tax_total >= 0),
  total            app.money_amount not null default 0 check (total >= 0),
  converted_invoice_id uuid references sales.invoices (id) on delete restrict,
  cancelled_at     timestamptz,
  cancelled_by     uuid references app.users (id),
  cancel_reason    text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, order_no),
  constraint sales_orders_non_draft_has_number check (
    status = 'DRAFT' or status = 'CANCELLED' or order_no is not null
  ),
  constraint sales_orders_cancel_has_reason check (
    status <> 'CANCELLED' or length(btrim(coalesce(cancel_reason, ''))) > 0
  )
);

comment on table sales.sales_orders is
  'Customer sales order. No GL. Convert to invoice via sales.convert_order_to_invoice.';

create table sales.sales_order_lines (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  sales_order_id     uuid not null references sales.sales_orders (id) on delete cascade,
  line_no            integer not null check (line_no > 0),
  item_id            uuid references inv.items (id) on delete restrict,
  description        text not null check (length(btrim(description)) > 0),
  quantity           app.quantity not null check (quantity > 0),
  unit_price         app.money_amount not null check (unit_price >= 0),
  tax_code_id        uuid references app.tax_codes (id) on delete restrict,
  tax_amount         app.money_amount not null default 0 check (tax_amount >= 0),
  line_net           app.money_amount not null default 0 check (line_net >= 0),
  revenue_account_id uuid references gl.accounts (id) on delete restrict,
  created_at         timestamptz not null default now(),
  unique (sales_order_id, line_no)
);

-- ---------------------------------------------------------------------------
-- Credit notes
-- ---------------------------------------------------------------------------

create table sales.credit_notes (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  credit_no        text,
  status           sales.credit_note_status not null default 'DRAFT',
  customer_id      uuid not null references app.customers (id) on delete restrict,
  credit_date      date not null,
  currency_code    char(3) not null references app.currencies (code),
  warehouse_id     uuid references inv.warehouses (id) on delete restrict,
  invoice_id       uuid references sales.invoices (id) on delete restrict,
  notes            text,
  restock          boolean not null default false,
  subtotal         app.money_amount not null default 0 check (subtotal >= 0),
  tax_total        app.money_amount not null default 0 check (tax_total >= 0),
  total            app.money_amount not null default 0 check (total >= 0),
  journal_entry_id uuid references gl.journal_entry (id) on delete restrict,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, credit_no),
  constraint credit_notes_posted_has_number check (status = 'DRAFT' or credit_no is not null),
  constraint credit_notes_posted_has_journal check (status <> 'POSTED' or journal_entry_id is not null)
);

comment on table sales.credit_notes is
  'Customer credit note. Posting reverses AR / revenue / output tax; optional CUSTOMER_RETURN restock.';

create table sales.credit_note_lines (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  credit_note_id     uuid not null references sales.credit_notes (id) on delete cascade,
  line_no            integer not null check (line_no > 0),
  item_id            uuid references inv.items (id) on delete restrict,
  description        text not null check (length(btrim(description)) > 0),
  quantity           app.quantity not null check (quantity > 0),
  unit_price         app.money_amount not null check (unit_price >= 0),
  tax_code_id        uuid references app.tax_codes (id) on delete restrict,
  tax_amount         app.money_amount not null default 0 check (tax_amount >= 0),
  line_net           app.money_amount not null default 0 check (line_net >= 0),
  revenue_account_id uuid references gl.accounts (id) on delete restrict,
  stock_unit_id      uuid references inv.stock_units (id) on delete restrict,
  stock_lot_id       uuid references inv.stock_lots (id) on delete restrict,
  unit_cost_base     app.money_amount check (unit_cost_base is null or unit_cost_base >= 0),
  created_at         timestamptz not null default now(),
  unique (credit_note_id, line_no)
);

create table sales.credit_note_allocations (
  id             uuid primary key default gen_random_uuid(),
  entity_id      uuid not null references app.entities (id) on delete restrict,
  credit_note_id uuid not null references sales.credit_notes (id) on delete cascade,
  invoice_id     uuid not null references sales.invoices (id) on delete restrict,
  amount         app.money_amount not null check (amount > 0),
  created_at     timestamptz not null default now(),
  unique (credit_note_id, invoice_id)
);

-- ---------------------------------------------------------------------------
-- Debit notes
-- ---------------------------------------------------------------------------

create table sales.debit_notes (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  debit_no         text,
  status           sales.debit_note_status not null default 'DRAFT',
  customer_id      uuid not null references app.customers (id) on delete restrict,
  debit_date       date not null,
  currency_code    char(3) not null references app.currencies (code),
  notes            text,
  subtotal         app.money_amount not null default 0 check (subtotal >= 0),
  tax_total        app.money_amount not null default 0 check (tax_total >= 0),
  total            app.money_amount not null default 0 check (total >= 0),
  journal_entry_id uuid references gl.journal_entry (id) on delete restrict,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, debit_no),
  constraint debit_notes_posted_has_number check (status = 'DRAFT' or debit_no is not null),
  constraint debit_notes_posted_has_journal check (status <> 'POSTED' or journal_entry_id is not null)
);

create table sales.debit_note_lines (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  debit_note_id      uuid not null references sales.debit_notes (id) on delete cascade,
  line_no            integer not null check (line_no > 0),
  item_id            uuid references inv.items (id) on delete restrict,
  description        text not null check (length(btrim(description)) > 0),
  quantity           app.quantity not null check (quantity > 0),
  unit_price         app.money_amount not null check (unit_price >= 0),
  tax_code_id        uuid references app.tax_codes (id) on delete restrict,
  tax_amount         app.money_amount not null default 0 check (tax_amount >= 0),
  line_net           app.money_amount not null default 0 check (line_net >= 0),
  revenue_account_id uuid references gl.accounts (id) on delete restrict,
  created_at         timestamptz not null default now(),
  unique (debit_note_id, line_no)
);

-- ---------------------------------------------------------------------------
-- Refunds
-- ---------------------------------------------------------------------------

create table sales.refunds (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references app.entities (id) on delete restrict,
  refund_no        text,
  status           sales.refund_status not null default 'DRAFT',
  customer_id      uuid not null references app.customers (id) on delete restrict,
  refund_date      date not null,
  currency_code    char(3) not null references app.currencies (code),
  amount           app.money_amount not null check (amount > 0),
  bank_account_id  uuid not null references gl.accounts (id) on delete restrict,
  memo             text,
  journal_entry_id uuid references gl.journal_entry (id) on delete restrict,
  reverse_reason   text,
  reversed_at      timestamptz,
  reversed_by      uuid references app.users (id),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid,
  updated_by       uuid,
  unique (entity_id, refund_no),
  constraint refunds_posted_has_number check (status = 'DRAFT' or refund_no is not null),
  constraint refunds_posted_has_journal check (status <> 'POSTED' or journal_entry_id is not null),
  constraint refunds_reversed_has_reason check (
    status <> 'REVERSED' or length(btrim(coalesce(reverse_reason, ''))) > 0
  )
);

comment on table sales.refunds is
  'Customer refund: CR bank / DR AR (money out). Mirror reverse of a customer receipt.';

create table sales.refund_allocations (
  id          uuid primary key default gen_random_uuid(),
  entity_id   uuid not null references app.entities (id) on delete restrict,
  refund_id   uuid not null references sales.refunds (id) on delete cascade,
  invoice_id  uuid not null references sales.invoices (id) on delete restrict,
  amount      app.money_amount not null check (amount > 0),
  created_at  timestamptz not null default now(),
  unique (refund_id, invoice_id)
);

create index quotations_entity_status_idx on sales.quotations (entity_id, status, quotation_date desc);
create index sales_orders_entity_status_idx on sales.sales_orders (entity_id, status, order_date desc);
create index credit_notes_entity_status_idx on sales.credit_notes (entity_id, status, credit_date desc);
create index credit_note_allocations_invoice_idx on sales.credit_note_allocations (invoice_id);
create index debit_notes_entity_status_idx on sales.debit_notes (entity_id, status, debit_date desc);
create index refunds_entity_status_idx on sales.refunds (entity_id, status, refund_date desc);

-- Outstanding after receipts AND posted credit-note allocations.
create or replace view sales.v_invoice_balances
with (security_invoker = true) as
select
  i.id,
  i.entity_id,
  i.total,
  coalesce((
    select sum(a.amount)
      from sales.receipt_allocations a
      join sales.receipts r on r.id = a.receipt_id
     where a.invoice_id = i.id and r.status = 'POSTED'
  ), 0)
  + coalesce((
    select sum(a.amount)
      from sales.credit_note_allocations a
      join sales.credit_notes c on c.id = a.credit_note_id
     where a.invoice_id = i.id and c.status = 'POSTED'
  ), 0) as allocated,
  i.total
  - coalesce((
    select sum(a.amount)
      from sales.receipt_allocations a
      join sales.receipts r on r.id = a.receipt_id
     where a.invoice_id = i.id and r.status = 'POSTED'
  ), 0)
  - coalesce((
    select sum(a.amount)
      from sales.credit_note_allocations a
      join sales.credit_notes c on c.id = a.credit_note_id
     where a.invoice_id = i.id and c.status = 'POSTED'
  ), 0) as outstanding
from sales.invoices i;

comment on view sales.v_invoice_balances is
  'Issued-invoice outstanding after posted receipts and posted credit-note allocations.';

-- ---------------------------------------------------------------------------
-- Guards (draft-only edits; status via SECURITY DEFINER)
-- ---------------------------------------------------------------------------

create or replace function sales.fn_guard_doc_status()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status::text not in ('DRAFT') then
      raise exception 'Only a draft document can be deleted'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if current_setting('sales.allow_status_change', true) is distinct from 'on' then
    if tg_op = 'UPDATE' and old.status::text <> 'DRAFT' then
      raise exception 'A non-draft document cannot be amended'
        using errcode = 'restrict_violation';
    end if;
    if new.status is distinct from coalesce(old.status, new.status) then
      raise exception 'Change document status through the sales.* functions'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger quotations_guard
  before insert or update or delete on sales.quotations
  for each row execute function sales.fn_guard_doc_status();
create trigger sales_orders_guard
  before insert or update or delete on sales.sales_orders
  for each row execute function sales.fn_guard_doc_status();
create trigger credit_notes_guard
  before insert or update or delete on sales.credit_notes
  for each row execute function sales.fn_guard_doc_status();
create trigger debit_notes_guard
  before insert or update or delete on sales.debit_notes
  for each row execute function sales.fn_guard_doc_status();
create trigger refunds_guard
  before insert or update or delete on sales.refunds
  for each row execute function sales.fn_guard_doc_status();

create or replace function sales.fn_guard_quotation_line()
returns trigger language plpgsql set search_path = pg_catalog, public as $$
declare v_status sales.quotation_status;
begin
  select status into v_status from sales.quotations where id = coalesce(new.quotation_id, old.quotation_id);
  if v_status <> 'DRAFT' and current_setting('sales.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on a non-draft quotation cannot be amended' using errcode = 'restrict_violation';
  end if;
  return coalesce(new, old);
end; $$;

create trigger quotation_lines_guard
  before insert or update or delete on sales.quotation_lines
  for each row execute function sales.fn_guard_quotation_line();

create or replace function sales.fn_guard_sales_order_line()
returns trigger language plpgsql set search_path = pg_catalog, public as $$
declare v_status sales.sales_order_status;
begin
  select status into v_status from sales.sales_orders where id = coalesce(new.sales_order_id, old.sales_order_id);
  if v_status <> 'DRAFT' and current_setting('sales.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on a non-draft sales order cannot be amended' using errcode = 'restrict_violation';
  end if;
  return coalesce(new, old);
end; $$;

create trigger sales_order_lines_guard
  before insert or update or delete on sales.sales_order_lines
  for each row execute function sales.fn_guard_sales_order_line();

create or replace function sales.fn_guard_credit_note_line()
returns trigger language plpgsql set search_path = pg_catalog, public as $$
declare v_status sales.credit_note_status;
begin
  select status into v_status from sales.credit_notes where id = coalesce(new.credit_note_id, old.credit_note_id);
  if v_status <> 'DRAFT' and current_setting('sales.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on a posted credit note cannot be amended' using errcode = 'restrict_violation';
  end if;
  return coalesce(new, old);
end; $$;

create trigger credit_note_lines_guard
  before insert or update or delete on sales.credit_note_lines
  for each row execute function sales.fn_guard_credit_note_line();

create or replace function sales.fn_guard_debit_note_line()
returns trigger language plpgsql set search_path = pg_catalog, public as $$
declare v_status sales.debit_note_status;
begin
  select status into v_status from sales.debit_notes where id = coalesce(new.debit_note_id, old.debit_note_id);
  if v_status <> 'DRAFT' and current_setting('sales.allow_status_change', true) is distinct from 'on' then
    raise exception 'Lines on a posted debit note cannot be amended' using errcode = 'restrict_violation';
  end if;
  return coalesce(new, old);
end; $$;

create trigger debit_note_lines_guard
  before insert or update or delete on sales.debit_note_lines
  for each row execute function sales.fn_guard_debit_note_line();

select app.enable_updated_at('sales.quotations');
select app.enable_updated_at('sales.sales_orders');
select app.enable_updated_at('sales.credit_notes');
select app.enable_updated_at('sales.debit_notes');
select app.enable_updated_at('sales.refunds');
select app.enable_audit('sales.quotations');
select app.enable_audit('sales.quotation_lines');
select app.enable_audit('sales.sales_orders');
select app.enable_audit('sales.sales_order_lines');
select app.enable_audit('sales.credit_notes');
select app.enable_audit('sales.credit_note_lines');
select app.enable_audit('sales.credit_note_allocations');
select app.enable_audit('sales.debit_notes');
select app.enable_audit('sales.debit_note_lines');
select app.enable_audit('sales.refunds');
select app.enable_audit('sales.refund_allocations');

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

create or replace function sales.ar_account(p_entity_id uuid, p_customer_id uuid)
returns uuid
language plpgsql
stable
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_ar uuid;
begin
  select coalesce(
    c.ar_account_id,
    (select a.id from gl.accounts a
      where a.entity_id = p_entity_id
        and a.control_type = 'ACCOUNTS_RECEIVABLE'
        and a.is_postable
      order by a.code
      limit 1)
  ) into v_ar
  from app.customers c
  where c.id = p_customer_id and c.entity_id = p_entity_id;

  if v_ar is null then
    raise exception 'No receivables control account is configured' using errcode = 'no_data_found';
  end if;
  return v_ar;
end;
$$;

create or replace function sales.recompute_quotation_totals(p_id uuid)
returns void language plpgsql set search_path = pg_catalog, public as $$
begin
  update sales.quotations q
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select quotation_id, sum(line_net) as subtotal, sum(tax_amount) as tax_total
        from sales.quotation_lines where quotation_id = p_id group by quotation_id
    ) x
   where q.id = p_id and q.id = x.quotation_id;
  if not found then
    update sales.quotations set subtotal = 0, tax_total = 0, total = 0 where id = p_id;
  end if;
end;
$$;

create or replace function sales.recompute_sales_order_totals(p_id uuid)
returns void language plpgsql set search_path = pg_catalog, public as $$
begin
  update sales.sales_orders o
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select sales_order_id, sum(line_net) as subtotal, sum(tax_amount) as tax_total
        from sales.sales_order_lines where sales_order_id = p_id group by sales_order_id
    ) x
   where o.id = p_id and o.id = x.sales_order_id;
  if not found then
    update sales.sales_orders set subtotal = 0, tax_total = 0, total = 0 where id = p_id;
  end if;
end;
$$;

create or replace function sales.recompute_credit_note_totals(p_id uuid)
returns void language plpgsql set search_path = pg_catalog, public as $$
begin
  update sales.credit_notes c
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select credit_note_id, sum(line_net) as subtotal, sum(tax_amount) as tax_total
        from sales.credit_note_lines where credit_note_id = p_id group by credit_note_id
    ) x
   where c.id = p_id and c.id = x.credit_note_id;
  if not found then
    update sales.credit_notes set subtotal = 0, tax_total = 0, total = 0 where id = p_id;
  end if;
end;
$$;

create or replace function sales.recompute_debit_note_totals(p_id uuid)
returns void language plpgsql set search_path = pg_catalog, public as $$
begin
  update sales.debit_notes d
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select debit_note_id, sum(line_net) as subtotal, sum(tax_amount) as tax_total
        from sales.debit_note_lines where debit_note_id = p_id group by debit_note_id
    ) x
   where d.id = p_id and d.id = x.debit_note_id;
  if not found then
    update sales.debit_notes set subtotal = 0, tax_total = 0, total = 0 where id = p_id;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- Quotations
-- ---------------------------------------------------------------------------

create or replace function sales.save_quotation(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id       uuid := nullif(p_payload ->> 'quotation_id', '')::uuid;
  v_customer uuid := (p_payload ->> 'customer_id')::uuid;
  v_date     date := (p_payload ->> 'quotation_date')::date;
  v_currency char(3);
  v_line     jsonb;
  v_line_no  integer := 0;
  v_qty      numeric;
  v_price    numeric;
  v_net      numeric;
  v_tax      numeric;
  v_rate     numeric;
  v_tax_id   uuid;
  v_status   sales.quotation_status;
begin
  perform app.require_permission(p_entity_id, 'sales.invoice.create');

  if v_customer is null or v_date is null then
    raise exception 'customer_id and quotation_date are required' using errcode = 'null_value_not_allowed';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer and c.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from sales.quotations where id = v_id and entity_id = p_entity_id;
    if not found then raise exception 'Quotation was not found' using errcode = 'no_data_found'; end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft quotation can be saved' using errcode = 'restrict_violation';
    end if;

    update sales.quotations
       set customer_id = v_customer,
           quotation_date = v_date,
           valid_until = nullif(p_payload ->> 'valid_until', '')::date,
           currency_code = v_currency,
           payment_terms_id = nullif(p_payload ->> 'payment_terms_id', '')::uuid,
           warehouse_id = nullif(p_payload ->> 'warehouse_id', '')::uuid,
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id;
    delete from sales.quotation_lines where quotation_id = v_id;
  else
    insert into sales.quotations (
      entity_id, customer_id, quotation_date, valid_until, currency_code,
      payment_terms_id, warehouse_id, notes, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, nullif(p_payload ->> 'valid_until', '')::date, v_currency,
      nullif(p_payload ->> 'payment_terms_id', '')::uuid,
      nullif(p_payload ->> 'warehouse_id', '')::uuid,
      nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    ) returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no using errcode = 'null_value_not_allowed';
      end if;
      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);
      insert into sales.quotation_lines (
        entity_id, quotation_id, line_no, item_id, description,
        quantity, unit_price, tax_code_id, tax_amount, line_net, revenue_account_id
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'revenue_account_id', '')::uuid
      );
    end loop;
  end if;

  perform sales.recompute_quotation_totals(v_id);
  return v_id;
end;
$$;

create or replace function sales.send_quotation(p_quotation_id uuid)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_q sales.quotations%rowtype;
  v_no text;
begin
  perform app.require_permission(
    (select entity_id from sales.quotations where id = p_quotation_id),
    'sales.invoice.issue'
  );
  select * into v_q from sales.quotations where id = p_quotation_id for update;
  if not found then raise exception 'Quotation was not found' using errcode = 'no_data_found'; end if;
  if v_q.status = 'SENT' then return v_q.quotation_no; end if;
  if v_q.status <> 'DRAFT' then
    raise exception 'Only a draft quotation can be sent' using errcode = 'restrict_violation';
  end if;
  if not exists (select 1 from sales.quotation_lines where quotation_id = v_q.id) then
    raise exception 'A quotation needs at least one line' using errcode = 'check_violation';
  end if;
  v_no := app.next_document_number(v_q.entity_id, 'QT', v_q.quotation_date);
  perform set_config('sales.allow_status_change', 'on', true);
  update sales.quotations set status = 'SENT', quotation_no = v_no where id = v_q.id;
  perform set_config('sales.allow_status_change', '', true);
  return v_no;
end;
$$;

create or replace function sales.accept_quotation(p_quotation_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare v_q sales.quotations%rowtype;
begin
  perform app.require_permission(
    (select entity_id from sales.quotations where id = p_quotation_id),
    'sales.invoice.create'
  );
  select * into v_q from sales.quotations where id = p_quotation_id for update;
  if not found then raise exception 'Quotation was not found' using errcode = 'no_data_found'; end if;
  if v_q.status not in ('DRAFT', 'SENT') then
    raise exception 'Only a draft or sent quotation can be accepted' using errcode = 'restrict_violation';
  end if;
  if v_q.quotation_no is null then
    perform sales.send_quotation(p_quotation_id);
  end if;
  perform set_config('sales.allow_status_change', 'on', true);
  update sales.quotations set status = 'ACCEPTED' where id = p_quotation_id;
  perform set_config('sales.allow_status_change', '', true);
end;
$$;

create or replace function sales.cancel_quotation(p_quotation_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_q sales.quotations%rowtype;
  v_reason text := btrim(coalesce(p_reason, ''));
begin
  perform app.require_permission(
    (select entity_id from sales.quotations where id = p_quotation_id),
    'sales.invoice.create'
  );
  if length(v_reason) < 5 then
    raise exception 'A cancel needs a reason of at least five characters' using errcode = 'check_violation';
  end if;
  select * into v_q from sales.quotations where id = p_quotation_id for update;
  if not found then raise exception 'Quotation was not found' using errcode = 'no_data_found'; end if;
  if v_q.status = 'ACCEPTED' and v_q.converted_invoice_id is not null then
    raise exception 'A converted quotation cannot be cancelled' using errcode = 'restrict_violation';
  end if;
  if v_q.status = 'CANCELLED' then return; end if;
  perform set_config('sales.allow_status_change', 'on', true);
  update sales.quotations
     set status = 'CANCELLED', cancel_reason = v_reason,
         cancelled_at = now(), cancelled_by = app.acting_user_id()
   where id = p_quotation_id;
  perform set_config('sales.allow_status_change', '', true);
end;
$$;

create or replace function sales.convert_quotation_to_invoice(p_quotation_id uuid)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_q        sales.quotations%rowtype;
  v_invoice  uuid;
  v_lines    jsonb := '[]'::jsonb;
  v_line     record;
begin
  perform app.require_permission(
    (select entity_id from sales.quotations where id = p_quotation_id),
    'sales.invoice.create'
  );
  select * into v_q from sales.quotations where id = p_quotation_id for update;
  if not found then raise exception 'Quotation was not found' using errcode = 'no_data_found'; end if;
  if v_q.converted_invoice_id is not null then return v_q.converted_invoice_id; end if;
  if v_q.status = 'CANCELLED' then
    raise exception 'A cancelled quotation cannot be converted' using errcode = 'restrict_violation';
  end if;

  for v_line in
    select * from sales.quotation_lines where quotation_id = v_q.id order by line_no
  loop
    v_lines := v_lines || jsonb_build_object(
      'item_id', v_line.item_id,
      'description', v_line.description,
      'quantity', v_line.quantity,
      'unit_price', v_line.unit_price,
      'tax_code_id', v_line.tax_code_id,
      'revenue_account_id', v_line.revenue_account_id
    );
  end loop;

  v_invoice := sales.save_invoice(v_q.entity_id, jsonb_build_object(
    'customer_id', v_q.customer_id,
    'invoice_date', current_date,
    'currency_code', v_q.currency_code,
    'payment_terms_id', v_q.payment_terms_id,
    'warehouse_id', v_q.warehouse_id,
    'notes', coalesce('Converted from quotation ' || v_q.quotation_no, v_q.notes),
    'lines', v_lines
  ));

  if v_q.status = 'DRAFT' then
    perform sales.send_quotation(p_quotation_id);
  end if;

  perform set_config('sales.allow_status_change', 'on', true);
  update sales.quotations
     set status = 'ACCEPTED', converted_invoice_id = v_invoice
   where id = p_quotation_id;
  perform set_config('sales.allow_status_change', '', true);

  return v_invoice;
end;
$$;

-- ---------------------------------------------------------------------------
-- Sales orders
-- ---------------------------------------------------------------------------

create or replace function sales.save_sales_order(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id       uuid := nullif(p_payload ->> 'sales_order_id', '')::uuid;
  v_customer uuid := (p_payload ->> 'customer_id')::uuid;
  v_date     date := (p_payload ->> 'order_date')::date;
  v_currency char(3);
  v_line     jsonb;
  v_line_no  integer := 0;
  v_qty      numeric;
  v_price    numeric;
  v_net      numeric;
  v_tax      numeric;
  v_rate     numeric;
  v_tax_id   uuid;
  v_status   sales.sales_order_status;
begin
  perform app.require_permission(p_entity_id, 'sales.invoice.create');

  if v_customer is null or v_date is null then
    raise exception 'customer_id and order_date are required' using errcode = 'null_value_not_allowed';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer and c.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from sales.sales_orders where id = v_id and entity_id = p_entity_id;
    if not found then raise exception 'Sales order was not found' using errcode = 'no_data_found'; end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft sales order can be saved' using errcode = 'restrict_violation';
    end if;
    update sales.sales_orders
       set customer_id = v_customer,
           order_date = v_date,
           currency_code = v_currency,
           payment_terms_id = nullif(p_payload ->> 'payment_terms_id', '')::uuid,
           warehouse_id = nullif(p_payload ->> 'warehouse_id', '')::uuid,
           customer_po = nullif(p_payload ->> 'customer_po', ''),
           notes = nullif(p_payload ->> 'notes', ''),
           quotation_id = nullif(p_payload ->> 'quotation_id', '')::uuid,
           updated_by = app.acting_user_id()
     where id = v_id;
    delete from sales.sales_order_lines where sales_order_id = v_id;
  else
    insert into sales.sales_orders (
      entity_id, customer_id, order_date, currency_code, payment_terms_id,
      warehouse_id, customer_po, notes, quotation_id, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, v_currency,
      nullif(p_payload ->> 'payment_terms_id', '')::uuid,
      nullif(p_payload ->> 'warehouse_id', '')::uuid,
      nullif(p_payload ->> 'customer_po', ''),
      nullif(p_payload ->> 'notes', ''),
      nullif(p_payload ->> 'quotation_id', '')::uuid,
      app.acting_user_id(), app.acting_user_id()
    ) returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no using errcode = 'null_value_not_allowed';
      end if;
      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);
      insert into sales.sales_order_lines (
        entity_id, sales_order_id, line_no, item_id, description,
        quantity, unit_price, tax_code_id, tax_amount, line_net, revenue_account_id
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'revenue_account_id', '')::uuid
      );
    end loop;
  end if;

  perform sales.recompute_sales_order_totals(v_id);
  return v_id;
end;
$$;

create or replace function sales.confirm_sales_order(p_order_id uuid)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_o sales.sales_orders%rowtype;
  v_no text;
begin
  perform app.require_permission(
    (select entity_id from sales.sales_orders where id = p_order_id),
    'sales.invoice.issue'
  );
  select * into v_o from sales.sales_orders where id = p_order_id for update;
  if not found then raise exception 'Sales order was not found' using errcode = 'no_data_found'; end if;
  if v_o.status = 'CONFIRMED' then return v_o.order_no; end if;
  if v_o.status <> 'DRAFT' then
    raise exception 'Only a draft sales order can be confirmed' using errcode = 'restrict_violation';
  end if;
  if not exists (select 1 from sales.sales_order_lines where sales_order_id = v_o.id) then
    raise exception 'A sales order needs at least one line' using errcode = 'check_violation';
  end if;
  v_no := app.next_document_number(v_o.entity_id, 'SO', v_o.order_date);
  perform set_config('sales.allow_status_change', 'on', true);
  update sales.sales_orders set status = 'CONFIRMED', order_no = v_no where id = v_o.id;
  perform set_config('sales.allow_status_change', '', true);
  return v_no;
end;
$$;

create or replace function sales.cancel_sales_order(p_order_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_o sales.sales_orders%rowtype;
  v_reason text := btrim(coalesce(p_reason, ''));
begin
  perform app.require_permission(
    (select entity_id from sales.sales_orders where id = p_order_id),
    'sales.invoice.create'
  );
  if length(v_reason) < 5 then
    raise exception 'A cancel needs a reason of at least five characters' using errcode = 'check_violation';
  end if;
  select * into v_o from sales.sales_orders where id = p_order_id for update;
  if not found then raise exception 'Sales order was not found' using errcode = 'no_data_found'; end if;
  if v_o.converted_invoice_id is not null then
    raise exception 'A converted sales order cannot be cancelled' using errcode = 'restrict_violation';
  end if;
  if v_o.status = 'CANCELLED' then return; end if;
  perform set_config('sales.allow_status_change', 'on', true);
  update sales.sales_orders
     set status = 'CANCELLED', cancel_reason = v_reason,
         cancelled_at = now(), cancelled_by = app.acting_user_id()
   where id = p_order_id;
  perform set_config('sales.allow_status_change', '', true);
end;
$$;

create or replace function sales.convert_order_to_invoice(p_order_id uuid)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_o        sales.sales_orders%rowtype;
  v_invoice  uuid;
  v_lines    jsonb := '[]'::jsonb;
  v_line     record;
begin
  perform app.require_permission(
    (select entity_id from sales.sales_orders where id = p_order_id),
    'sales.invoice.create'
  );
  select * into v_o from sales.sales_orders where id = p_order_id for update;
  if not found then raise exception 'Sales order was not found' using errcode = 'no_data_found'; end if;
  if v_o.converted_invoice_id is not null then return v_o.converted_invoice_id; end if;
  if v_o.status = 'CANCELLED' then
    raise exception 'A cancelled sales order cannot be converted' using errcode = 'restrict_violation';
  end if;

  for v_line in
    select * from sales.sales_order_lines where sales_order_id = v_o.id order by line_no
  loop
    v_lines := v_lines || jsonb_build_object(
      'item_id', v_line.item_id,
      'description', v_line.description,
      'quantity', v_line.quantity,
      'unit_price', v_line.unit_price,
      'tax_code_id', v_line.tax_code_id,
      'revenue_account_id', v_line.revenue_account_id
    );
  end loop;

  v_invoice := sales.save_invoice(v_o.entity_id, jsonb_build_object(
    'customer_id', v_o.customer_id,
    'invoice_date', current_date,
    'currency_code', v_o.currency_code,
    'payment_terms_id', v_o.payment_terms_id,
    'warehouse_id', v_o.warehouse_id,
    'customer_po', v_o.customer_po,
    'notes', coalesce('Converted from order ' || v_o.order_no, v_o.notes),
    'lines', v_lines
  ));

  if v_o.status = 'DRAFT' then
    perform sales.confirm_sales_order(p_order_id);
  end if;

  perform set_config('sales.allow_status_change', 'on', true);
  update sales.sales_orders set converted_invoice_id = v_invoice where id = p_order_id;
  perform set_config('sales.allow_status_change', '', true);

  return v_invoice;
end;
$$;

-- ---------------------------------------------------------------------------
-- Credit notes
-- ---------------------------------------------------------------------------

create or replace function sales.save_credit_note(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id       uuid := nullif(p_payload ->> 'credit_note_id', '')::uuid;
  v_customer uuid := (p_payload ->> 'customer_id')::uuid;
  v_date     date := (p_payload ->> 'credit_date')::date;
  v_currency char(3);
  v_line     jsonb;
  v_alloc    jsonb;
  v_line_no  integer := 0;
  v_qty      numeric;
  v_price    numeric;
  v_net      numeric;
  v_tax      numeric;
  v_rate     numeric;
  v_tax_id   uuid;
  v_status   sales.credit_note_status;
begin
  perform app.require_permission(p_entity_id, 'sales.invoice.create');

  if v_customer is null or v_date is null then
    raise exception 'customer_id and credit_date are required' using errcode = 'null_value_not_allowed';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer and c.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from sales.credit_notes where id = v_id and entity_id = p_entity_id;
    if not found then raise exception 'Credit note was not found' using errcode = 'no_data_found'; end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft credit note can be saved' using errcode = 'restrict_violation';
    end if;
    update sales.credit_notes
       set customer_id = v_customer,
           credit_date = v_date,
           currency_code = v_currency,
           warehouse_id = nullif(p_payload ->> 'warehouse_id', '')::uuid,
           invoice_id = nullif(p_payload ->> 'invoice_id', '')::uuid,
           notes = nullif(p_payload ->> 'notes', ''),
           restock = coalesce((p_payload ->> 'restock')::boolean, false),
           updated_by = app.acting_user_id()
     where id = v_id;
    delete from sales.credit_note_lines where credit_note_id = v_id;
    delete from sales.credit_note_allocations where credit_note_id = v_id;
  else
    insert into sales.credit_notes (
      entity_id, customer_id, credit_date, currency_code, warehouse_id,
      invoice_id, notes, restock, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, v_currency,
      nullif(p_payload ->> 'warehouse_id', '')::uuid,
      nullif(p_payload ->> 'invoice_id', '')::uuid,
      nullif(p_payload ->> 'notes', ''),
      coalesce((p_payload ->> 'restock')::boolean, false),
      app.acting_user_id(), app.acting_user_id()
    ) returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no using errcode = 'null_value_not_allowed';
      end if;
      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);
      insert into sales.credit_note_lines (
        entity_id, credit_note_id, line_no, item_id, description,
        quantity, unit_price, tax_code_id, tax_amount, line_net,
        revenue_account_id, stock_unit_id, stock_lot_id, unit_cost_base
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'revenue_account_id', '')::uuid,
        nullif(v_line ->> 'stock_unit_id', '')::uuid,
        nullif(v_line ->> 'stock_lot_id', '')::uuid,
        nullif(v_line ->> 'unit_cost_base', '')::numeric
      );
    end loop;
  end if;

  if jsonb_typeof(p_payload -> 'allocations') = 'array' then
    for v_alloc in select * from jsonb_array_elements(p_payload -> 'allocations')
    loop
      insert into sales.credit_note_allocations (entity_id, credit_note_id, invoice_id, amount)
      values (
        p_entity_id, v_id,
        (v_alloc ->> 'invoice_id')::uuid,
        (v_alloc ->> 'amount')::numeric
      );
    end loop;
  end if;

  perform sales.recompute_credit_note_totals(v_id);
  return v_id;
end;
$$;

create or replace function sales.post_credit_note(
  p_credit_note_id  uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_cn         sales.credit_notes%rowtype;
  v_customer   app.customers%rowtype;
  v_ar         uuid;
  v_entry_id   uuid;
  v_credit_no  text;
  v_lines      jsonb := '[]'::jsonb;
  v_line       record;
  v_tax        record;
  v_revenue    uuid;
  v_alloc      record;
  v_key        text;
begin
  perform app.require_permission(
    (select entity_id from sales.credit_notes where id = p_credit_note_id),
    'sales.invoice.issue'
  );

  select * into v_cn from sales.credit_notes where id = p_credit_note_id for update;
  if not found then raise exception 'Credit note was not found' using errcode = 'no_data_found'; end if;
  if v_cn.status = 'POSTED' then return v_cn.journal_entry_id; end if;
  if v_cn.status <> 'DRAFT' then
    raise exception 'Only a draft credit note can be posted' using errcode = 'restrict_violation';
  end if;

  perform sales.recompute_credit_note_totals(v_cn.id);
  select * into v_cn from sales.credit_notes where id = v_cn.id;

  if v_cn.total <= 0 then
    raise exception 'A credit note needs at least one line with a positive amount'
      using errcode = 'check_violation';
  end if;

  select * into v_customer from app.customers where id = v_cn.customer_id;
  v_ar := sales.ar_account(v_cn.entity_id, v_cn.customer_id);

  for v_alloc in
    select a.invoice_id, a.amount, i.invoice_no, i.status, i.customer_id, i.currency_code, bal.outstanding
      from sales.credit_note_allocations a
      join sales.invoices i on i.id = a.invoice_id
      join sales.v_invoice_balances bal on bal.id = i.id
     where a.credit_note_id = v_cn.id
  loop
    if v_alloc.status <> 'ISSUED' then
      raise exception 'Credits can only be applied to issued invoices' using errcode = 'restrict_violation';
    end if;
    if v_alloc.customer_id <> v_cn.customer_id then
      raise exception 'Invoice % belongs to a different customer', v_alloc.invoice_no
        using errcode = 'restrict_violation';
    end if;
    if v_alloc.currency_code <> v_cn.currency_code then
      raise exception 'Invoice % currency mismatch', v_alloc.invoice_no
        using errcode = 'check_violation';
    end if;
    if v_alloc.amount > v_alloc.outstanding then
      raise exception 'Allocation of % to invoice % exceeds outstanding %',
        v_alloc.amount, v_alloc.invoice_no, v_alloc.outstanding
        using errcode = 'check_violation';
    end if;
  end loop;

  -- Optional restock via CUSTOMER_RETURN (positive inbound quantity).
  if v_cn.restock then
    if v_cn.warehouse_id is null then
      raise exception 'Restock requires warehouse_id' using errcode = 'null_value_not_allowed';
    end if;
    for v_line in
      select * from sales.credit_note_lines
       where credit_note_id = v_cn.id
         and item_id is not null
         and (stock_unit_id is not null or stock_lot_id is not null or unit_cost_base is not null)
       order by line_no
    loop
      v_key := case when p_idempotency_key is not null
        then p_idempotency_key || ':return:' || v_line.line_no else null end;
      perform inv.post_movement(
        p_entity_id => v_cn.entity_id,
        p_item_id => v_line.item_id,
        p_warehouse_id => v_cn.warehouse_id,
        p_movement_type => 'CUSTOMER_RETURN',
        p_movement_date => v_cn.credit_date,
        p_quantity => v_line.quantity,
        p_stock_unit_id => v_line.stock_unit_id,
        p_stock_lot_id => v_line.stock_lot_id,
        p_unit_cost_base => v_line.unit_cost_base,
        p_source_type => 'SALES_CREDIT_NOTE',
        p_source_id => v_cn.id,
        p_source_line_id => v_line.id,
        p_reference => null,
        p_notes => v_line.description,
        p_idempotency_key => v_key
      );
    end loop;
  end if;

  -- Reverse of invoice: DR revenue, DR output tax, CR AR.
  for v_line in
    select l.* from sales.credit_note_lines l
     where l.credit_note_id = v_cn.id order by l.line_no
  loop
    v_revenue := coalesce(
      v_line.revenue_account_id,
      (select i.revenue_account_id from inv.items i where i.id = v_line.item_id),
      gl.setting_account(v_cn.entity_id, 'DEFAULT_REVENUE')
    );
    v_lines := v_lines || jsonb_build_object(
      'account_id', v_revenue,
      'currency_code', v_cn.currency_code,
      'debit', v_line.line_net,
      'credit', 0,
      'memo', v_line.description,
      'customer_id', v_cn.customer_id,
      'item_id', v_line.item_id
    );
  end loop;

  for v_tax in
    select t.output_tax_account_id as account_id, sum(l.tax_amount) as amount
      from sales.credit_note_lines l
      join app.tax_codes t on t.id = l.tax_code_id
     where l.credit_note_id = v_cn.id and l.tax_amount > 0
     group by t.output_tax_account_id
  loop
    if v_tax.account_id is null then
      raise exception 'Tax code is missing an output tax account' using errcode = 'no_data_found';
    end if;
    v_lines := v_lines || jsonb_build_object(
      'account_id', v_tax.account_id,
      'currency_code', v_cn.currency_code,
      'debit', v_tax.amount,
      'credit', 0,
      'memo', 'Output tax reversal',
      'customer_id', v_cn.customer_id
    );
  end loop;

  v_lines := v_lines || jsonb_build_object(
    'account_id', v_ar,
    'currency_code', v_cn.currency_code,
    'debit', 0,
    'credit', v_cn.total,
    'memo', 'Accounts receivable',
    'customer_id', v_cn.customer_id
  );

  v_credit_no := app.next_document_number(v_cn.entity_id, 'CN', v_cn.credit_date);

  v_entry_id := gl.post_entry(
    v_cn.entity_id,
    jsonb_build_object(
      'entry_date', v_cn.credit_date,
      'source_type', 'SALES_CREDIT_NOTE',
      'source_id', v_cn.id,
      'source_document_no', v_credit_no,
      'description', 'Credit note ' || v_credit_no || ' · ' || v_customer.legal_name,
      'lines', v_lines
    ),
    p_idempotency_key
  );

  perform set_config('sales.allow_status_change', 'on', true);
  update sales.credit_notes
     set status = 'POSTED', credit_no = v_credit_no, journal_entry_id = v_entry_id
   where id = v_cn.id;
  perform set_config('sales.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Debit notes (simple AR increase)
-- ---------------------------------------------------------------------------

create or replace function sales.save_debit_note(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id       uuid := nullif(p_payload ->> 'debit_note_id', '')::uuid;
  v_customer uuid := (p_payload ->> 'customer_id')::uuid;
  v_date     date := (p_payload ->> 'debit_date')::date;
  v_currency char(3);
  v_line     jsonb;
  v_line_no  integer := 0;
  v_qty      numeric;
  v_price    numeric;
  v_net      numeric;
  v_tax      numeric;
  v_rate     numeric;
  v_tax_id   uuid;
  v_status   sales.debit_note_status;
begin
  perform app.require_permission(p_entity_id, 'sales.invoice.create');

  if v_customer is null or v_date is null then
    raise exception 'customer_id and debit_date are required' using errcode = 'null_value_not_allowed';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer and c.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from sales.debit_notes where id = v_id and entity_id = p_entity_id;
    if not found then raise exception 'Debit note was not found' using errcode = 'no_data_found'; end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft debit note can be saved' using errcode = 'restrict_violation';
    end if;
    update sales.debit_notes
       set customer_id = v_customer, debit_date = v_date, currency_code = v_currency,
           notes = nullif(p_payload ->> 'notes', ''), updated_by = app.acting_user_id()
     where id = v_id;
    delete from sales.debit_note_lines where debit_note_id = v_id;
  else
    insert into sales.debit_notes (
      entity_id, customer_id, debit_date, currency_code, notes, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, v_currency, nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    ) returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no using errcode = 'null_value_not_allowed';
      end if;
      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);
      insert into sales.debit_note_lines (
        entity_id, debit_note_id, line_no, item_id, description,
        quantity, unit_price, tax_code_id, tax_amount, line_net, revenue_account_id
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'revenue_account_id', '')::uuid
      );
    end loop;
  end if;

  perform sales.recompute_debit_note_totals(v_id);
  return v_id;
end;
$$;

create or replace function sales.post_debit_note(
  p_debit_note_id   uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_dn        sales.debit_notes%rowtype;
  v_customer  app.customers%rowtype;
  v_ar        uuid;
  v_entry_id  uuid;
  v_debit_no  text;
  v_lines     jsonb := '[]'::jsonb;
  v_line      record;
  v_tax       record;
  v_revenue   uuid;
begin
  perform app.require_permission(
    (select entity_id from sales.debit_notes where id = p_debit_note_id),
    'sales.invoice.issue'
  );

  select * into v_dn from sales.debit_notes where id = p_debit_note_id for update;
  if not found then raise exception 'Debit note was not found' using errcode = 'no_data_found'; end if;
  if v_dn.status = 'POSTED' then return v_dn.journal_entry_id; end if;
  if v_dn.status <> 'DRAFT' then
    raise exception 'Only a draft debit note can be posted' using errcode = 'restrict_violation';
  end if;

  perform sales.recompute_debit_note_totals(v_dn.id);
  select * into v_dn from sales.debit_notes where id = v_dn.id;
  if v_dn.total <= 0 then
    raise exception 'A debit note needs at least one line with a positive amount'
      using errcode = 'check_violation';
  end if;

  select * into v_customer from app.customers where id = v_dn.customer_id;
  v_ar := sales.ar_account(v_dn.entity_id, v_dn.customer_id);

  for v_line in
    select * from sales.debit_note_lines where debit_note_id = v_dn.id order by line_no
  loop
    v_revenue := coalesce(
      v_line.revenue_account_id,
      (select i.revenue_account_id from inv.items i where i.id = v_line.item_id),
      gl.setting_account(v_dn.entity_id, 'DEFAULT_REVENUE')
    );
    v_lines := v_lines || jsonb_build_object(
      'account_id', v_revenue,
      'currency_code', v_dn.currency_code,
      'credit', v_line.line_net,
      'debit', 0,
      'memo', v_line.description,
      'customer_id', v_dn.customer_id,
      'item_id', v_line.item_id
    );
  end loop;

  for v_tax in
    select t.output_tax_account_id as account_id, sum(l.tax_amount) as amount
      from sales.debit_note_lines l
      join app.tax_codes t on t.id = l.tax_code_id
     where l.debit_note_id = v_dn.id and l.tax_amount > 0
     group by t.output_tax_account_id
  loop
    if v_tax.account_id is null then
      raise exception 'Tax code is missing an output tax account' using errcode = 'no_data_found';
    end if;
    v_lines := v_lines || jsonb_build_object(
      'account_id', v_tax.account_id,
      'currency_code', v_dn.currency_code,
      'credit', v_tax.amount,
      'debit', 0,
      'memo', 'Output tax',
      'customer_id', v_dn.customer_id
    );
  end loop;

  v_lines := v_lines || jsonb_build_object(
    'account_id', v_ar,
    'currency_code', v_dn.currency_code,
    'debit', v_dn.total,
    'credit', 0,
    'memo', 'Accounts receivable',
    'customer_id', v_dn.customer_id
  );

  v_debit_no := app.next_document_number(v_dn.entity_id, 'DN', v_dn.debit_date);
  v_entry_id := gl.post_entry(
    v_dn.entity_id,
    jsonb_build_object(
      'entry_date', v_dn.debit_date,
      'source_type', 'SALES_DEBIT_NOTE',
      'source_id', v_dn.id,
      'source_document_no', v_debit_no,
      'description', 'Debit note ' || v_debit_no || ' · ' || v_customer.legal_name,
      'lines', v_lines
    ),
    p_idempotency_key
  );

  perform set_config('sales.allow_status_change', 'on', true);
  update sales.debit_notes
     set status = 'POSTED', debit_no = v_debit_no, journal_entry_id = v_entry_id
   where id = v_dn.id;
  perform set_config('sales.allow_status_change', '', true);
  return v_entry_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Refunds (money out: CR bank / DR AR)
-- ---------------------------------------------------------------------------

create or replace function sales.save_refund(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id       uuid := nullif(p_payload ->> 'refund_id', '')::uuid;
  v_customer uuid := (p_payload ->> 'customer_id')::uuid;
  v_date     date := (p_payload ->> 'refund_date')::date;
  v_amount   numeric := (p_payload ->> 'amount')::numeric;
  v_bank     uuid := (p_payload ->> 'bank_account_id')::uuid;
  v_currency char(3);
  v_status   sales.refund_status;
  v_alloc    jsonb;
begin
  perform app.require_permission(p_entity_id, 'sales.payment.create');

  if v_customer is null or v_date is null or v_amount is null or v_bank is null then
    raise exception 'customer_id, refund_date, amount and bank_account_id are required'
      using errcode = 'null_value_not_allowed';
  end if;
  if v_amount <= 0 then
    raise exception 'Refund amount must be greater than zero' using errcode = 'check_violation';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer and c.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from sales.refunds where id = v_id and entity_id = p_entity_id;
    if not found then raise exception 'Refund was not found' using errcode = 'no_data_found'; end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft refund can be saved' using errcode = 'restrict_violation';
    end if;
    update sales.refunds
       set customer_id = v_customer, refund_date = v_date, currency_code = v_currency,
           amount = v_amount, bank_account_id = v_bank,
           memo = nullif(p_payload ->> 'memo', ''), updated_by = app.acting_user_id()
     where id = v_id;
    delete from sales.refund_allocations where refund_id = v_id;
  else
    insert into sales.refunds (
      entity_id, customer_id, refund_date, currency_code, amount,
      bank_account_id, memo, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, v_currency, v_amount,
      v_bank, nullif(p_payload ->> 'memo', ''),
      app.acting_user_id(), app.acting_user_id()
    ) returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'allocations') = 'array' then
    for v_alloc in select * from jsonb_array_elements(p_payload -> 'allocations')
    loop
      insert into sales.refund_allocations (entity_id, refund_id, invoice_id, amount)
      values (p_entity_id, v_id, (v_alloc ->> 'invoice_id')::uuid, (v_alloc ->> 'amount')::numeric);
    end loop;
  end if;

  return v_id;
end;
$$;

create or replace function sales.post_refund(
  p_refund_id       uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_rf         sales.refunds%rowtype;
  v_customer   app.customers%rowtype;
  v_ar         uuid;
  v_bank       gl.accounts%rowtype;
  v_entry_id   uuid;
  v_refund_no  text;
begin
  perform app.require_permission(
    (select entity_id from sales.refunds where id = p_refund_id),
    'sales.payment.create'
  );

  select * into v_rf from sales.refunds where id = p_refund_id for update;
  if not found then raise exception 'Refund was not found' using errcode = 'no_data_found'; end if;
  if v_rf.status = 'POSTED' then return v_rf.journal_entry_id; end if;
  if v_rf.status <> 'DRAFT' then
    raise exception 'Only a draft refund can be posted' using errcode = 'restrict_violation';
  end if;

  select * into v_customer from app.customers where id = v_rf.customer_id;
  select * into v_bank from gl.accounts where id = v_rf.bank_account_id;
  if not found or v_bank.entity_id <> v_rf.entity_id or not v_bank.is_postable then
    raise exception 'Bank account is not a postable account of this entity'
      using errcode = 'restrict_violation';
  end if;
  if v_bank.control_type is distinct from 'BANK' and v_bank.control_type is distinct from 'CASH' then
    raise exception 'Refunds must be drawn from a cash or bank account'
      using errcode = 'restrict_violation';
  end if;

  v_ar := sales.ar_account(v_rf.entity_id, v_rf.customer_id);
  v_refund_no := app.next_document_number(v_rf.entity_id, 'RF', v_rf.refund_date);

  -- Money out: DR AR, CR bank (reverse of receipt which is DR bank / CR AR).
  v_entry_id := gl.post_entry(
    v_rf.entity_id,
    jsonb_build_object(
      'entry_date', v_rf.refund_date,
      'source_type', 'CUSTOMER_REFUND',
      'source_id', v_rf.id,
      'source_document_no', v_refund_no,
      'description', 'Refund ' || v_refund_no || ' · ' || v_customer.legal_name,
      'lines', jsonb_build_array(
        jsonb_build_object(
          'account_id', v_ar,
          'currency_code', v_rf.currency_code,
          'debit', v_rf.amount,
          'credit', 0,
          'memo', 'Accounts receivable',
          'customer_id', v_rf.customer_id
        ),
        jsonb_build_object(
          'account_id', v_rf.bank_account_id,
          'currency_code', v_rf.currency_code,
          'debit', 0,
          'credit', v_rf.amount,
          'memo', coalesce(v_rf.memo, 'Customer refund'),
          'customer_id', v_rf.customer_id
        )
      )
    ),
    p_idempotency_key
  );

  perform set_config('sales.allow_status_change', 'on', true);
  update sales.refunds
     set status = 'POSTED', refund_no = v_refund_no, journal_entry_id = v_entry_id
   where id = v_rf.id;
  perform set_config('sales.allow_status_change', '', true);
  return v_entry_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Customer statement
-- ---------------------------------------------------------------------------

create or replace function sales.customer_statement(
  p_entity_id   uuid,
  p_customer_id uuid,
  p_as_of       date default current_date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_result jsonb;
begin
  perform app.require_permission(p_entity_id, 'sales.invoice.create');

  if not exists (
    select 1 from app.customers c
     where c.id = p_customer_id and c.entity_id = p_entity_id
  ) then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  select jsonb_build_object(
    'customer_id', p_customer_id,
    'as_of', p_as_of,
    'open_invoices', coalesce((
      select jsonb_agg(jsonb_build_object(
        'invoice_id', i.id,
        'invoice_no', i.invoice_no,
        'invoice_date', i.invoice_date,
        'due_date', i.due_date,
        'total', i.total,
        'outstanding', bal.outstanding,
        'currency_code', i.currency_code
      ) order by i.invoice_date, i.invoice_no)
        from sales.invoices i
        join sales.v_invoice_balances bal on bal.id = i.id
       where i.entity_id = p_entity_id
         and i.customer_id = p_customer_id
         and i.status = 'ISSUED'
         and i.invoice_date <= p_as_of
         and bal.outstanding > 0
    ), '[]'::jsonb),
    'recent_activity', coalesce((
      select jsonb_agg(x.row order by x.sort_date desc, x.doc_no)
        from (
          select i.invoice_date as sort_date, i.invoice_no as doc_no,
                 jsonb_build_object(
                   'type', 'INVOICE',
                   'id', i.id,
                   'doc_no', i.invoice_no,
                   'doc_date', i.invoice_date,
                   'amount', i.total,
                   'status', i.status::text
                 ) as row
            from sales.invoices i
           where i.entity_id = p_entity_id and i.customer_id = p_customer_id
             and i.invoice_date <= p_as_of and i.status in ('ISSUED', 'VOIDED')
          union all
          select r.receipt_date, r.receipt_no,
                 jsonb_build_object(
                   'type', 'RECEIPT',
                   'id', r.id,
                   'doc_no', r.receipt_no,
                   'doc_date', r.receipt_date,
                   'amount', r.amount,
                   'status', r.status::text
                 )
            from sales.receipts r
           where r.entity_id = p_entity_id and r.customer_id = p_customer_id
             and r.receipt_date <= p_as_of and r.status = 'POSTED'
          union all
          select c.credit_date, c.credit_no,
                 jsonb_build_object(
                   'type', 'CREDIT_NOTE',
                   'id', c.id,
                   'doc_no', c.credit_no,
                   'doc_date', c.credit_date,
                   'amount', c.total,
                   'status', c.status::text
                 )
            from sales.credit_notes c
           where c.entity_id = p_entity_id and c.customer_id = p_customer_id
             and c.credit_date <= p_as_of and c.status = 'POSTED'
          union all
          select d.debit_date, d.debit_no,
                 jsonb_build_object(
                   'type', 'DEBIT_NOTE',
                   'id', d.id,
                   'doc_no', d.debit_no,
                   'doc_date', d.debit_date,
                   'amount', d.total,
                   'status', d.status::text
                 )
            from sales.debit_notes d
           where d.entity_id = p_entity_id and d.customer_id = p_customer_id
             and d.debit_date <= p_as_of and d.status = 'POSTED'
          union all
          select f.refund_date, f.refund_no,
                 jsonb_build_object(
                   'type', 'REFUND',
                   'id', f.id,
                   'doc_no', f.refund_no,
                   'doc_date', f.refund_date,
                   'amount', f.amount,
                   'status', f.status::text
                 )
            from sales.refunds f
           where f.entity_id = p_entity_id and f.customer_id = p_customer_id
             and f.refund_date <= p_as_of and f.status = 'POSTED'
        ) x
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

-- ---------------------------------------------------------------------------
-- Privileges & RLS
-- ---------------------------------------------------------------------------

grant select on all tables in schema sales to skyjet_app, authenticated;
grant select on sales.v_invoice_balances to skyjet_app, authenticated;

grant execute on function
  sales.ar_account(uuid, uuid),
  sales.recompute_quotation_totals(uuid),
  sales.recompute_sales_order_totals(uuid),
  sales.recompute_credit_note_totals(uuid),
  sales.recompute_debit_note_totals(uuid),
  sales.save_quotation(uuid, jsonb),
  sales.send_quotation(uuid),
  sales.accept_quotation(uuid),
  sales.cancel_quotation(uuid, text),
  sales.convert_quotation_to_invoice(uuid),
  sales.save_sales_order(uuid, jsonb),
  sales.confirm_sales_order(uuid),
  sales.cancel_sales_order(uuid, text),
  sales.convert_order_to_invoice(uuid),
  sales.save_credit_note(uuid, jsonb),
  sales.post_credit_note(uuid, text),
  sales.save_debit_note(uuid, jsonb),
  sales.post_debit_note(uuid, text),
  sales.save_refund(uuid, jsonb),
  sales.post_refund(uuid, text),
  sales.customer_statement(uuid, uuid, date)
to skyjet_app;

select app.enforce_rls_everywhere();

select app.apply_entity_read_policy(t) from (values
  ('sales.quotations'::regclass),
  ('sales.quotation_lines'::regclass),
  ('sales.sales_orders'::regclass),
  ('sales.sales_order_lines'::regclass),
  ('sales.credit_notes'::regclass),
  ('sales.credit_note_lines'::regclass),
  ('sales.credit_note_allocations'::regclass),
  ('sales.debit_notes'::regclass),
  ('sales.debit_note_lines'::regclass),
  ('sales.refunds'::regclass),
  ('sales.refund_allocations'::regclass)
) as tables(t);
