-- ===========================================================================
-- Sales receipts (cash sales) + per-entity document layout preferences
-- ===========================================================================

set search_path = pg_catalog, public, extensions;

insert into gl.journal_sources (code, name, is_manual, description) values
  ('SALES_RECEIPT', 'Sales Receipt', false, 'Cash / card sale deposited immediately')
on conflict (code) do nothing;

insert into app.document_types (code, name, description) values
  ('SR',  'Sales Receipt',    'Customer-facing sales receipt number'),
  ('SRJ', 'Sales Receipt JE', 'Journal generated by posting a sales receipt')
on conflict (code) do nothing;

create or replace function gl.document_type_for_source(p_source_type text)
returns text
language sql
immutable
set search_path = pg_catalog, public
as $$
  select case p_source_type
    when 'MANUAL'            then 'JE'
    when 'OPENING_BALANCE'   then 'OB'
    when 'REVERSAL'          then 'REV'
    when 'FX_REVALUATION'    then 'FXR'
    when 'YEAR_END_CLOSE'    then 'YEC'
    when 'STOCK_MOVEMENT'    then 'STK'
    when 'SALES_INVOICE'     then 'SI'
    when 'CUSTOMER_RECEIPT'  then 'CRP'
    when 'SALES_CREDIT_NOTE' then 'SI'
    when 'SALES_DEBIT_NOTE'  then 'SDN'
    when 'CUSTOMER_REFUND'   then 'CRF'
    when 'SALES_RECEIPT'     then 'SRJ'
    when 'PURCHASE_BILL'     then 'APB'
    when 'SUPPLIER_PAYMENT'  then 'SPY'
    when 'SUPPLIER_CREDIT'   then 'SCJ'
    else 'JE'
  end;
$$;

-- ---------------------------------------------------------------------------
-- Layout preferences (gear button on documents)
-- ---------------------------------------------------------------------------

create table if not exists app.document_layout_settings (
  id            uuid primary key default gen_random_uuid(),
  entity_id     uuid not null references app.entities (id) on delete restrict,
  document_type text not null check (document_type in (
    'INVOICE', 'SALES_RECEIPT', 'ESTIMATE', 'CREDIT_NOTE', 'SALES_ORDER'
  )),
  settings      jsonb not null default '{}'::jsonb,
  updated_at    timestamptz not null default now(),
  updated_by    uuid,
  unique (entity_id, document_type)
);

comment on table app.document_layout_settings is
  'Per-entity display toggles and column labels for customer-facing documents.';

select app.enable_updated_at('app.document_layout_settings');
select app.apply_entity_read_policy('app.document_layout_settings'::regclass);

grant select on app.document_layout_settings to skyjet_app, authenticated;

create or replace function app.default_document_layout(p_document_type text)
returns jsonb
language sql
immutable
set search_path = pg_catalog, public
as $$
  select jsonb_build_object(
    'show_logo', true,
    'show_ship_to', true,
    'show_document_no', true,
    'show_document_date', true,
    'show_due_date', true,
    'show_terms', true,
    'show_customer_email', true,
    'show_customer_contact', true,
    'show_company_registration', true,
    'show_table', true,
    'columns', jsonb_build_object(
      'line_no', jsonb_build_object('visible', true, 'label', '#'),
      'service_date', jsonb_build_object('visible', false, 'label', 'Service date'),
      'product', jsonb_build_object('visible', true, 'label', 'Product/service'),
      'sku', jsonb_build_object('visible', true, 'label', 'SKU'),
      'description', jsonb_build_object('visible', true, 'label', 'Description'),
      'qty', jsonb_build_object('visible', true, 'label', 'Qty'),
      'rate', jsonb_build_object('visible', true, 'label', 'Rate'),
      'amount', jsonb_build_object('visible', true, 'label', 'Amount')
    )
  );
$$;

create or replace function app.get_document_layout(p_entity_id uuid, p_document_type text)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_settings jsonb;
begin
  select settings into v_settings
    from app.document_layout_settings
   where entity_id = p_entity_id and document_type = p_document_type;
  return app.default_document_layout(p_document_type) || coalesce(v_settings, '{}'::jsonb);
end;
$$;

create or replace function app.save_document_layout(
  p_entity_id     uuid,
  p_document_type text,
  p_settings      jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
begin
  perform app.require_permission(p_entity_id, 'settings.manage');

  if p_document_type not in ('INVOICE', 'SALES_RECEIPT', 'ESTIMATE', 'CREDIT_NOTE', 'SALES_ORDER') then
    raise exception 'Unknown document type %', p_document_type using errcode = 'check_violation';
  end if;

  insert into app.document_layout_settings (entity_id, document_type, settings, updated_by)
  values (p_entity_id, p_document_type, coalesce(p_settings, '{}'::jsonb), app.acting_user_id())
  on conflict (entity_id, document_type) do update
    set settings = excluded.settings,
        updated_by = app.acting_user_id();

  return app.get_document_layout(p_entity_id, p_document_type);
end;
$$;

grant execute on function
  app.default_document_layout(text),
  app.get_document_layout(uuid, text),
  app.save_document_layout(uuid, text, jsonb)
to skyjet_app;

-- ---------------------------------------------------------------------------
-- Sales receipts
-- ---------------------------------------------------------------------------

create type sales.sales_receipt_status as enum ('DRAFT', 'POSTED', 'VOIDED');

create table sales.sales_receipts (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  receipt_no         text,
  status             sales.sales_receipt_status not null default 'DRAFT',
  customer_id        uuid not null references app.customers (id) on delete restrict,
  receipt_date       date not null,
  currency_code      char(3) not null references app.currencies (code),
  payment_terms_id   uuid references app.payment_terms (id) on delete restrict,
  warehouse_id       uuid references inv.warehouses (id) on delete restrict,
  bank_account_id    uuid not null references gl.accounts (id) on delete restrict,
  bill_email         text,
  ship_to_name       text,
  ship_to_address    text,
  customer_po        text,
  notes              text,
  subtotal           app.money_amount not null default 0 check (subtotal >= 0),
  tax_total          app.money_amount not null default 0 check (tax_total >= 0),
  total              app.money_amount not null default 0 check (total >= 0),
  journal_entry_id   uuid references gl.journal_entry (id) on delete restrict,
  void_reason        text,
  voided_at          timestamptz,
  voided_by          uuid references app.users (id),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  created_by         uuid,
  updated_by         uuid,
  unique (entity_id, receipt_no),
  constraint sales_receipts_posted_has_number check (status = 'DRAFT' or receipt_no is not null),
  constraint sales_receipts_posted_has_journal check (status <> 'POSTED' or journal_entry_id is not null),
  constraint sales_receipts_void_has_reason check (
    status <> 'VOIDED' or length(btrim(coalesce(void_reason, ''))) > 0
  )
);

create table sales.sales_receipt_lines (
  id                 uuid primary key default gen_random_uuid(),
  entity_id          uuid not null references app.entities (id) on delete restrict,
  sales_receipt_id   uuid not null references sales.sales_receipts (id) on delete cascade,
  line_no            integer not null check (line_no > 0),
  item_id            uuid references inv.items (id) on delete restrict,
  description        text not null check (length(btrim(description)) > 0),
  service_date       date,
  quantity           app.quantity not null check (quantity > 0),
  unit_price         app.money_amount not null check (unit_price >= 0),
  tax_code_id        uuid references app.tax_codes (id) on delete restrict,
  tax_amount         app.money_amount not null default 0 check (tax_amount >= 0),
  line_net           app.money_amount not null default 0 check (line_net >= 0),
  revenue_account_id uuid references gl.accounts (id) on delete restrict,
  stock_unit_id      uuid references inv.stock_units (id) on delete restrict,
  stock_lot_id       uuid references inv.stock_lots (id) on delete restrict,
  created_at         timestamptz not null default now(),
  unique (sales_receipt_id, line_no)
);

create index sales_receipts_entity_status_idx
  on sales.sales_receipts (entity_id, status, receipt_date desc);
create index sales_receipt_lines_receipt_idx
  on sales.sales_receipt_lines (sales_receipt_id, line_no);

create or replace function sales.fn_guard_sales_receipt()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'DELETE' then
    if old.status <> 'DRAFT' then
      raise exception 'Only a draft sales receipt can be deleted'
        using errcode = 'restrict_violation';
    end if;
    return old;
  end if;

  if tg_op = 'UPDATE'
     and old.status is distinct from new.status
     and current_setting('sales.allow_status_change', true) is distinct from 'on' then
    raise exception 'Change sales receipt status through sales.post_sales_receipt / void_sales_receipt'
      using errcode = 'restrict_violation';
  end if;

  if tg_op = 'UPDATE' and old.status <> 'DRAFT' and new.status = old.status then
    if current_setting('sales.allow_status_change', true) is distinct from 'on' then
      raise exception 'A posted sales receipt cannot be amended'
        using errcode = 'restrict_violation';
    end if;
  end if;

  return new;
end;
$$;

create trigger sales_receipts_guard
  before insert or update or delete on sales.sales_receipts
  for each row execute function sales.fn_guard_sales_receipt();

create or replace function sales.fn_guard_sales_receipt_line()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_status sales.sales_receipt_status;
begin
  select status into v_status
    from sales.sales_receipts
   where id = coalesce(new.sales_receipt_id, old.sales_receipt_id);
  if v_status <> 'DRAFT' then
    raise exception 'Lines on a non-draft sales receipt cannot be amended'
      using errcode = 'restrict_violation';
  end if;
  return coalesce(new, old);
end;
$$;

create trigger sales_receipt_lines_guard
  before insert or update or delete on sales.sales_receipt_lines
  for each row execute function sales.fn_guard_sales_receipt_line();

select app.enable_updated_at('sales.sales_receipts');
select app.enable_audit('sales.sales_receipts');
select app.enable_audit('sales.sales_receipt_lines');

select app.enforce_rls_everywhere();

select app.apply_entity_read_policy(t) from (values
  ('app.document_layout_settings'::regclass),
  ('sales.sales_receipts'::regclass),
  ('sales.sales_receipt_lines'::regclass)
) as v(t);

create or replace function sales.recompute_sales_receipt_totals(p_receipt_id uuid)
returns void
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  update sales.sales_receipts r
     set subtotal = coalesce(x.subtotal, 0),
         tax_total = coalesce(x.tax_total, 0),
         total = coalesce(x.subtotal, 0) + coalesce(x.tax_total, 0)
    from (
      select sales_receipt_id,
             sum(line_net) as subtotal,
             sum(tax_amount) as tax_total
        from sales.sales_receipt_lines
       where sales_receipt_id = p_receipt_id
       group by sales_receipt_id
    ) x
   where r.id = p_receipt_id and r.id = x.sales_receipt_id;

  if not found then
    update sales.sales_receipts
       set subtotal = 0, tax_total = 0, total = 0
     where id = p_receipt_id;
  end if;
end;
$$;

create or replace function sales.save_sales_receipt(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id         uuid := nullif(p_payload ->> 'sales_receipt_id', '')::uuid;
  v_customer   uuid := (p_payload ->> 'customer_id')::uuid;
  v_date       date := (p_payload ->> 'receipt_date')::date;
  v_bank       uuid := (p_payload ->> 'bank_account_id')::uuid;
  v_currency   char(3);
  v_terms      uuid := nullif(p_payload ->> 'payment_terms_id', '')::uuid;
  v_warehouse  uuid := nullif(p_payload ->> 'warehouse_id', '')::uuid;
  v_line       jsonb;
  v_line_no    integer := 0;
  v_qty        numeric;
  v_price      numeric;
  v_net        numeric;
  v_tax        numeric;
  v_rate       numeric;
  v_tax_id     uuid;
  v_status     sales.sales_receipt_status;
begin
  perform app.require_permission(p_entity_id, 'sales.invoice.create');

  if v_customer is null or v_date is null or v_bank is null then
    raise exception 'customer_id, receipt_date and bank_account_id are required'
      using errcode = 'null_value_not_allowed';
  end if;

  if not exists (
    select 1 from gl.accounts a
     where a.id = v_bank and a.entity_id = p_entity_id and a.is_postable
       and a.control_type in ('BANK', 'CASH')
  ) then
    raise exception 'Deposit account must be a cash or bank account of this entity'
      using errcode = 'restrict_violation';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer and c.entity_id = p_entity_id;
  if v_currency is null then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_id is not null then
    select status into v_status from sales.sales_receipts where id = v_id and entity_id = p_entity_id;
    if not found then raise exception 'Sales receipt was not found' using errcode = 'no_data_found'; end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft sales receipt can be saved' using errcode = 'restrict_violation';
    end if;
    update sales.sales_receipts
       set customer_id = v_customer,
           receipt_date = v_date,
           currency_code = v_currency,
           payment_terms_id = v_terms,
           warehouse_id = v_warehouse,
           bank_account_id = v_bank,
           bill_email = nullif(p_payload ->> 'bill_email', ''),
           ship_to_name = nullif(p_payload ->> 'ship_to_name', ''),
           ship_to_address = nullif(p_payload ->> 'ship_to_address', ''),
           customer_po = nullif(p_payload ->> 'customer_po', ''),
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id;
    delete from sales.sales_receipt_lines where sales_receipt_id = v_id;
  else
    insert into sales.sales_receipts (
      entity_id, customer_id, receipt_date, currency_code, payment_terms_id,
      warehouse_id, bank_account_id, bill_email, ship_to_name, ship_to_address,
      customer_po, notes, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, v_currency, v_terms, v_warehouse, v_bank,
      nullif(p_payload ->> 'bill_email', ''),
      nullif(p_payload ->> 'ship_to_name', ''),
      nullif(p_payload ->> 'ship_to_address', ''),
      nullif(p_payload ->> 'customer_po', ''),
      nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    ) returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no
          using errcode = 'null_value_not_allowed';
      end if;
      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);
      insert into sales.sales_receipt_lines (
        entity_id, sales_receipt_id, line_no, item_id, description, service_date,
        quantity, unit_price, tax_code_id, tax_amount, line_net, revenue_account_id,
        stock_unit_id, stock_lot_id
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        nullif(v_line ->> 'service_date', '')::date,
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'revenue_account_id', '')::uuid,
        nullif(v_line ->> 'stock_unit_id', '')::uuid,
        nullif(v_line ->> 'stock_lot_id', '')::uuid
      );
    end loop;
  end if;

  perform sales.recompute_sales_receipt_totals(v_id);
  return v_id;
end;
$$;

create or replace function sales.post_sales_receipt(
  p_receipt_id      uuid,
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_rct          sales.sales_receipts%rowtype;
  v_customer     app.customers%rowtype;
  v_entry_id     uuid;
  v_receipt_no   text;
  v_lines        jsonb := '[]'::jsonb;
  v_line         record;
  v_tax          record;
  v_revenue      uuid;
  v_item         inv.items%rowtype;
  v_warehouse    uuid;
  v_needs_stock  boolean := false;
begin
  perform app.require_permission(
    (select entity_id from sales.sales_receipts where id = p_receipt_id),
    'sales.invoice.issue'
  );

  select * into v_rct from sales.sales_receipts where id = p_receipt_id for update;
  if not found then raise exception 'Sales receipt was not found' using errcode = 'no_data_found'; end if;
  if v_rct.status = 'POSTED' then return v_rct.journal_entry_id; end if;
  if v_rct.status <> 'DRAFT' then
    raise exception 'Only a draft sales receipt can be posted' using errcode = 'restrict_violation';
  end if;

  perform sales.recompute_sales_receipt_totals(v_rct.id);
  select * into v_rct from sales.sales_receipts where id = v_rct.id;

  if v_rct.total <= 0 then
    raise exception 'A sales receipt needs at least one line with a positive amount'
      using errcode = 'check_violation';
  end if;

  select * into v_customer from app.customers where id = v_rct.customer_id;

  select exists (
    select 1 from sales.sales_receipt_lines l
      join inv.items i on i.id = l.item_id
     where l.sales_receipt_id = v_rct.id and i.is_stocked
  ) into v_needs_stock;

  v_warehouse := v_rct.warehouse_id;
  if v_needs_stock then
    if v_warehouse is null then
      select w.id into v_warehouse from inv.warehouses w
       where w.entity_id = v_rct.entity_id and w.is_active and not w.is_consignment
       order by w.code limit 1;
    end if;
    if v_warehouse is null then
      raise exception 'A warehouse is required to post stocked sales receipt lines'
        using errcode = 'null_value_not_allowed';
    end if;
  end if;

  v_receipt_no := app.next_document_number(v_rct.entity_id, 'SR', v_rct.receipt_date);

  for v_line in
    select l.* from sales.sales_receipt_lines l
     where l.sales_receipt_id = v_rct.id and l.item_id is not null
     order by l.line_no
  loop
    select * into v_item from inv.items where id = v_line.item_id;
    if not found or not v_item.is_stocked then continue; end if;
    if v_item.tracking_mode = 'SERIAL' then
      if v_line.stock_unit_id is null then
        raise exception 'Line %: serialised item requires a stock unit', v_line.line_no
          using errcode = 'null_value_not_allowed';
      end if;
      perform inv.assert_unit_releasable(v_line.stock_unit_id, v_rct.receipt_date);
    elsif v_item.tracking_mode = 'LOT' and v_line.stock_lot_id is null then
      raise exception 'Line %: lot-tracked item requires a stock lot', v_line.line_no
        using errcode = 'null_value_not_allowed';
    end if;
    perform inv.post_movement(
      p_entity_id => v_rct.entity_id,
      p_item_id => v_line.item_id,
      p_warehouse_id => v_warehouse,
      p_movement_type => 'ISSUE',
      p_movement_date => v_rct.receipt_date,
      p_quantity => -v_line.quantity,
      p_stock_unit_id => v_line.stock_unit_id,
      p_stock_lot_id => v_line.stock_lot_id,
      p_source_type => 'SALES_RECEIPT',
      p_source_id => v_rct.id,
      p_source_line_id => v_line.id,
      p_reference => v_receipt_no,
      p_notes => v_line.description
    );
  end loop;

  for v_line in
    select l.* from sales.sales_receipt_lines l
     where l.sales_receipt_id = v_rct.id
     order by l.line_no
  loop
    v_revenue := coalesce(
      v_line.revenue_account_id,
      (select i.revenue_account_id from inv.items i where i.id = v_line.item_id),
      gl.setting_account(v_rct.entity_id, 'DEFAULT_REVENUE')
    );
    v_lines := v_lines || jsonb_build_object(
      'account_id', v_revenue, 'currency_code', v_rct.currency_code,
      'credit', v_line.line_net, 'debit', 0, 'memo', v_line.description,
      'customer_id', v_rct.customer_id, 'item_id', v_line.item_id
    );
  end loop;

  for v_tax in
    select t.output_tax_account_id as account_id, sum(l.tax_amount) as amount
      from sales.sales_receipt_lines l
      join app.tax_codes t on t.id = l.tax_code_id
     where l.sales_receipt_id = v_rct.id and l.tax_amount > 0
     group by t.output_tax_account_id
  loop
    if v_tax.account_id is null then
      raise exception 'Tax code is missing an output tax account' using errcode = 'no_data_found';
    end if;
    v_lines := v_lines || jsonb_build_object(
      'account_id', v_tax.account_id, 'currency_code', v_rct.currency_code,
      'credit', v_tax.amount, 'debit', 0, 'memo', 'Output tax',
      'customer_id', v_rct.customer_id
    );
  end loop;

  v_lines := v_lines || jsonb_build_object(
    'account_id', v_rct.bank_account_id, 'currency_code', v_rct.currency_code,
    'debit', v_rct.total, 'credit', 0, 'memo', 'Sales receipt deposit',
    'customer_id', v_rct.customer_id
  );

  v_entry_id := gl.post_entry(
    v_rct.entity_id,
    jsonb_build_object(
      'entry_date', v_rct.receipt_date,
      'source_type', 'SALES_RECEIPT',
      'source_id', v_rct.id,
      'source_document_no', v_receipt_no,
      'description', 'Sales receipt ' || v_receipt_no || ' · ' || v_customer.legal_name,
      'lines', v_lines
    ),
    p_idempotency_key
  );

  perform set_config('sales.allow_status_change', 'on', true);
  update sales.sales_receipts
     set status = 'POSTED',
         receipt_no = v_receipt_no,
         journal_entry_id = v_entry_id,
         warehouse_id = v_warehouse
   where id = v_rct.id;
  perform set_config('sales.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

create or replace function sales.void_sales_receipt(p_receipt_id uuid, p_reason text)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_rct      sales.sales_receipts%rowtype;
  v_entry_id uuid;
  v_reason   text := btrim(coalesce(p_reason, ''));
  v_mv       record;
begin
  perform app.require_permission(
    (select entity_id from sales.sales_receipts where id = p_receipt_id),
    'sales.invoice.void'
  );
  if length(v_reason) < 10 then
    raise exception 'A void needs a reason of at least ten characters'
      using errcode = 'check_violation';
  end if;

  select * into v_rct from sales.sales_receipts where id = p_receipt_id for update;
  if not found then raise exception 'Sales receipt was not found' using errcode = 'no_data_found'; end if;
  if v_rct.status <> 'POSTED' then
    raise exception 'Only a posted sales receipt can be voided' using errcode = 'restrict_violation';
  end if;

  for v_mv in
    select * from inv.stock_ledger
     where entity_id = v_rct.entity_id
       and source_type = 'SALES_RECEIPT'
       and source_id = v_rct.id
       and movement_type = 'ISSUE'
     order by id
  loop
    perform inv.post_movement(
      p_entity_id => v_rct.entity_id,
      p_item_id => v_mv.item_id,
      p_warehouse_id => v_mv.warehouse_id,
      p_movement_type => 'CUSTOMER_RETURN',
      p_movement_date => v_rct.receipt_date,
      p_quantity => abs(v_mv.quantity),
      p_bin_id => coalesce(
        v_mv.bin_id,
        (select b.id from inv.bins b where b.warehouse_id = v_mv.warehouse_id and b.code = 'MAIN' limit 1)
      ),
      p_stock_unit_id => v_mv.stock_unit_id,
      p_stock_lot_id => v_mv.stock_lot_id,
      p_unit_cost_base => v_mv.unit_cost_base,
      p_source_type => 'SALES_RECEIPT_VOID',
      p_source_id => v_rct.id,
      p_source_line_id => v_mv.source_line_id,
      p_reference => v_rct.receipt_no,
      p_notes => v_reason
    );
  end loop;

  v_entry_id := gl.reverse_entry(v_rct.journal_entry_id, v_reason, null, null);

  perform set_config('sales.allow_status_change', 'on', true);
  update sales.sales_receipts
     set status = 'VOIDED', void_reason = v_reason, voided_at = now(), voided_by = app.acting_user_id()
   where id = v_rct.id;
  perform set_config('sales.allow_status_change', '', true);

  return v_entry_id;
end;
$$;

grant execute on function
  sales.recompute_sales_receipt_totals(uuid),
  sales.save_sales_receipt(uuid, jsonb),
  sales.post_sales_receipt(uuid, text),
  sales.void_sales_receipt(uuid, text)
to skyjet_app;

-- Optional display fields already live on sales receipts; extend invoices too.
alter table sales.invoices
  add column if not exists bill_email text,
  add column if not exists ship_to_name text,
  add column if not exists ship_to_address text;

-- Also allow service_date on invoice lines for the layout column.
alter table sales.invoice_lines
  add column if not exists service_date date;

-- Persist layout-related invoice fields through save_invoice.
create or replace function sales.save_invoice(p_entity_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_id         uuid := nullif(p_payload ->> 'invoice_id', '')::uuid;
  v_customer   uuid := (p_payload ->> 'customer_id')::uuid;
  v_date       date := (p_payload ->> 'invoice_date')::date;
  v_due        date;
  v_currency   char(3);
  v_terms      uuid := nullif(p_payload ->> 'payment_terms_id', '')::uuid;
  v_warehouse  uuid := nullif(p_payload ->> 'warehouse_id', '')::uuid;
  v_line       jsonb;
  v_line_no    integer := 0;
  v_qty        numeric;
  v_price      numeric;
  v_net        numeric;
  v_tax        numeric;
  v_rate       numeric;
  v_tax_id     uuid;
  v_status     sales.invoice_status;
begin
  perform app.require_permission(p_entity_id, 'sales.invoice.create');

  if v_customer is null or v_date is null then
    raise exception 'customer_id and invoice_date are required' using errcode = 'null_value_not_allowed';
  end if;

  if not exists (
    select 1 from app.customers c
     where c.id = v_customer and c.entity_id = p_entity_id
  ) then
    raise exception 'Customer was not found in this entity' using errcode = 'no_data_found';
  end if;

  if v_warehouse is not null and not exists (
    select 1 from inv.warehouses w
     where w.id = v_warehouse and w.entity_id = p_entity_id and w.is_active
  ) then
    raise exception 'Warehouse was not found in this entity' using errcode = 'no_data_found';
  end if;

  select coalesce(nullif(p_payload ->> 'currency_code', ''), c.currency_code)
    into v_currency
    from app.customers c
   where c.id = v_customer;

  if v_terms is not null then
    select (v_date + make_interval(days => t.days_net))::date into v_due
      from app.payment_terms t
     where t.id = v_terms and t.entity_id = p_entity_id;
  end if;
  v_due := coalesce((nullif(p_payload ->> 'due_date', ''))::date, v_due, v_date);

  if v_id is not null then
    select status into v_status from sales.invoices where id = v_id and entity_id = p_entity_id;
    if not found then
      raise exception 'Invoice was not found' using errcode = 'no_data_found';
    end if;
    if v_status <> 'DRAFT' then
      raise exception 'Only a draft invoice can be saved' using errcode = 'restrict_violation';
    end if;

    update sales.invoices
       set customer_id = v_customer,
           invoice_date = v_date,
           due_date = v_due,
           currency_code = v_currency,
           payment_terms_id = v_terms,
           warehouse_id = v_warehouse,
           bill_email = nullif(p_payload ->> 'bill_email', ''),
           ship_to_name = nullif(p_payload ->> 'ship_to_name', ''),
           ship_to_address = nullif(p_payload ->> 'ship_to_address', ''),
           customer_po = nullif(p_payload ->> 'customer_po', ''),
           notes = nullif(p_payload ->> 'notes', ''),
           updated_by = app.acting_user_id()
     where id = v_id;

    delete from sales.invoice_lines where invoice_id = v_id;
  else
    insert into sales.invoices (
      entity_id, customer_id, invoice_date, due_date, currency_code,
      payment_terms_id, warehouse_id, bill_email, ship_to_name, ship_to_address,
      customer_po, notes, created_by, updated_by
    ) values (
      p_entity_id, v_customer, v_date, v_due, v_currency,
      v_terms, v_warehouse,
      nullif(p_payload ->> 'bill_email', ''),
      nullif(p_payload ->> 'ship_to_name', ''),
      nullif(p_payload ->> 'ship_to_address', ''),
      nullif(p_payload ->> 'customer_po', ''),
      nullif(p_payload ->> 'notes', ''),
      app.acting_user_id(), app.acting_user_id()
    )
    returning id into v_id;
  end if;

  if jsonb_typeof(p_payload -> 'lines') = 'array' then
    for v_line in select * from jsonb_array_elements(p_payload -> 'lines')
    loop
      v_line_no := v_line_no + 1;
      v_qty := (v_line ->> 'quantity')::numeric;
      v_price := (v_line ->> 'unit_price')::numeric;
      if v_qty is null or v_qty <= 0 or v_price is null or v_price < 0 then
        raise exception 'Line %: quantity must be positive and unit_price must be zero or more', v_line_no
          using errcode = 'check_violation';
      end if;
      if length(btrim(coalesce(v_line ->> 'description', ''))) = 0 then
        raise exception 'Line %: description is required', v_line_no
          using errcode = 'null_value_not_allowed';
      end if;

      v_net := round(v_qty * v_price, 4);
      v_tax_id := nullif(v_line ->> 'tax_code_id', '')::uuid;
      v_rate := 0;
      if v_tax_id is not null then
        select t.rate into v_rate
          from app.tax_codes t
         where t.id = v_tax_id and t.entity_id = p_entity_id and t.is_active;
        if not found then
          raise exception 'Line %: tax code was not found', v_line_no using errcode = 'no_data_found';
        end if;
      end if;
      v_tax := round(v_net * coalesce(v_rate, 0), 4);

      insert into sales.invoice_lines (
        entity_id, invoice_id, line_no, item_id, description, service_date,
        quantity, unit_price, tax_code_id, tax_amount, line_net, revenue_account_id,
        stock_unit_id, stock_lot_id
      ) values (
        p_entity_id, v_id, v_line_no,
        nullif(v_line ->> 'item_id', '')::uuid,
        btrim(v_line ->> 'description'),
        nullif(v_line ->> 'service_date', '')::date,
        v_qty, v_price, v_tax_id, v_tax, v_net,
        nullif(v_line ->> 'revenue_account_id', '')::uuid,
        nullif(v_line ->> 'stock_unit_id', '')::uuid,
        nullif(v_line ->> 'stock_lot_id', '')::uuid
      );
    end loop;
  end if;

  perform sales.recompute_invoice_totals(v_id);
  return v_id;
end;
$$;
